apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docs
  labels:
    app: {{ .Release.Name }}-docs
spec:
  replicas: {{ .Values.docs.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-docs
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-docs
    spec:
      containers:
        - name: docs
          image: {{ .Values.docs.image }}
          ports:
            - containerPort: {{ .Values.docs.port }}
          resources:
            {{- toYaml .Values.docs.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docs
spec:
  selector:
    app: {{ .Release.Name }}-docs
  ports:
    - port: 80
      targetPort: {{ .Values.docs.port }}
