// Code generated by packages/shared/scripts/emit-agent-catalog.cjs from
// packages/shared/src/agents/catalog.ts; DO NOT EDIT.

package domain

// launchCatalog is each agent's `launch` entry of the catalog, and the effort
// levels its models offer: the argument vectors a structured launch becomes.
// `<model>`, `<prompt>` and `<conversation>` are substituted whole; an effort
// spelling has `<effort>` and `<model>` replaced inside each word.
var launchCatalog = map[string]launchMap{
	"claude-code": {
		command:      "claude",
		model:        []string{"--model", "<model>"},
		defaultModel: "claude-opus-5-5",
		permission: map[string]launchLevel{
			"ask":  {argv: []string{"--permission-mode", "manual"}},
			"auto": {argv: []string{"--permission-mode", "acceptEdits"}},
			"full": {argv: []string{"--permission-mode", "bypassPermissions"}},
		},
		effort: launchLevel{argv: []string{"--effort", "<effort>"}},
		effortLevels: map[string][]string{
			"claude-opus-5-5":   {"low", "medium", "high", "xhigh", "max"},
			"claude-fable-5-1":  {"low", "medium", "high", "xhigh", "max"},
			"claude-sonnet-5-5": {"low", "medium", "high", "xhigh", "max"},
		},
		prompt:             []string{"<prompt>"},
		conversationCreate: []string{"--session-id", "<conversation>"},
		conversationResume: []string{"--resume", "<conversation>"},
	},
	"codex": {
		command:      "codex",
		always:       []string{"--no-daemon"},
		model:        []string{"--model", "<model>"},
		defaultModel: "gpt-5.6-sol",
		permission: map[string]launchLevel{
			"ask":  {argv: []string{"--ask-for-approval", "on-request", "--sandbox", "workspace-write"}},
			"auto": {argv: []string{"--approve-for-me"}},
			"full": {argv: []string{"--dangerously-bypass-approvals-and-sandbox"}},
		},
		effort: launchLevel{argv: []string{"-c", "model_reasoning_effort=<effort>"}},
		effortLevels: map[string][]string{
			"gpt-6-astra":   {"low", "medium", "high", "xhigh", "max", "ultra"},
			"gpt-5.6-sol":   {"low", "medium", "high", "xhigh", "max", "ultra"},
			"gpt-5.6-terra": {"low", "medium", "high", "xhigh", "max", "ultra"},
			"gpt-5.6-luna":  {"low", "medium", "high", "xhigh", "max"},
		},
		prompt:                  []string{"<prompt>"},
		conversationResume:      []string{"resume", "--last"},
		conversationResumeLeads: true,
	},
	"opencode": {
		command:      "opencode",
		model:        []string{"--model", "<model>"},
		defaultModel: "anthropic/claude-opus-5-5",
		permission: map[string]launchLevel{
			"ask":  {env: map[string]string{"OPENCODE_PERMISSION": "{\"edit\":\"ask\",\"bash\":\"ask\",\"webfetch\":\"ask\",\"websearch\":\"ask\",\"codesearch\":\"ask\"}"}},
			"auto": {env: map[string]string{"OPENCODE_PERMISSION": "{\"edit\":\"allow\",\"bash\":\"ask\",\"webfetch\":\"ask\",\"websearch\":\"ask\",\"codesearch\":\"ask\"}"}},
			"full": {argv: []string{"--auto"}},
		},
		effort:      launchLevel{env: map[string]string{"OPENCODE_CONFIG_CONTENT": "{\"agent\":{\"build\":{\"model\":\"<model>\",\"variant\":\"<effort>\"}}}"}},
		effortUnset: "none",
		effortLevels: map[string][]string{
			"anthropic/claude-opus-5-5":   {"low", "medium", "high", "xhigh", "max"},
			"anthropic/claude-fable-5-1":  {"low", "medium", "high", "xhigh", "max"},
			"anthropic/claude-sonnet-5-5": {"low", "medium", "high", "xhigh", "max"},
			"anthropic/claude-haiku-4-5":  {"none", "high", "max"},
			"openai/gpt-5.6-sol":          {"low", "medium", "high", "xhigh", "max"},
		},
		prompt:             []string{"--prompt", "<prompt>"},
		conversationResume: []string{"--continue"},
	},
	"grok": {
		command:      "grok",
		model:        []string{"--model", "<model>"},
		defaultModel: "grok-4.6",
		permission: map[string]launchLevel{
			"ask":  {argv: []string{"--permission-mode", "default"}},
			"auto": {argv: []string{"--permission-mode", "acceptEdits"}},
			"full": {argv: []string{"--permission-mode", "bypassPermissions"}},
		},
		effort: launchLevel{argv: []string{"--reasoning-effort", "<effort>"}},
		effortLevels: map[string][]string{
			"grok-4.7": {"minimal", "low", "medium", "high", "xhigh", "max"},
			"grok-4.6": {"minimal", "low", "medium", "high", "xhigh", "max"},
		},
		prompt:             []string{"<prompt>"},
		conversationCreate: []string{"--session-id", "<conversation>"},
		conversationResume: []string{"--resume", "<conversation>"},
	},
	"shell": {
		command: "",
	},
}

// loginTargets is each agent's `loginTargets` entry of the catalog: the
// vendor logins its screen may show that become a button. Hosts are
// compared for equality and a path, when set, must prefix the URL path.
var loginTargets = map[string][]LoginTarget{
	"claude-code": {{Host: "claude.ai"}, {Host: "console.anthropic.com"}},
	"codex":       {{Host: "auth.openai.com"}, {Host: "platform.openai.com"}, {Host: "chatgpt.com"}},
	"opencode":    {{Host: "opencode.ai"}, {Host: "claude.ai"}, {Host: "console.anthropic.com"}, {Host: "auth.openai.com"}, {Host: "chatgpt.com"}, {Host: "github.com", Path: "/login/device"}},
	"grok":        {{Host: "accounts.x.ai"}, {Host: "auth.x.ai"}},
}
