// Code generated by packages/shared/scripts/emit-agent-catalog.cjs from
// packages/shared/src/agents/catalog.ts; DO NOT EDIT.

package domain

// launchCatalog is each agent's `launch` entry of the catalog: the argument
// vectors a structured launch becomes. `<model>` and `<prompt>` are the two
// placeholders, substituted whole.
var launchCatalog = map[string]launchMap{
	"claude-code": {
		command: "claude",
		model:   []string{"--model", "<model>"},
		permission: map[string][]string{
			"ask":  {"--permission-mode", "manual"},
			"auto": {"--permission-mode", "acceptEdits"},
			"full": {"--permission-mode", "bypassPermissions"},
		},
		effort: map[string][]string{
			"minimal": {"--effort", "low"},
			"low":     {"--effort", "medium"},
			"medium":  {"--effort", "high"},
			"high":    {"--effort", "xhigh"},
			"max":     {"--effort", "max"},
		},
		prompt: []string{"<prompt>"},
	},
	"codex": {
		command: "codex",
		model:   []string{"--model", "<model>"},
		permission: map[string][]string{
			"ask":  {"--ask-for-approval", "on-request", "--sandbox", "workspace-write"},
			"auto": {"--approve-for-me"},
			"full": {"--dangerously-bypass-approvals-and-sandbox"},
		},
		effort: map[string][]string{
			"minimal": {"-c", "model_reasoning_effort=minimal"},
			"low":     {"-c", "model_reasoning_effort=low"},
			"medium":  {"-c", "model_reasoning_effort=medium"},
			"high":    {"-c", "model_reasoning_effort=high"},
			"max":     {"-c", "model_reasoning_effort=high"},
		},
		prompt: []string{"<prompt>"},
	},
}
