// Code generated by packages/shared/scripts/emit-session-file.cjs from
// packages/shared/src/protocol/session-file.ts; DO NOT EDIT.

package domain

// FileMaxBytes is the largest file a session takes.
const FileMaxBytes = 5242880

// CreateMaxFiles is how many files a session's first task may carry.
const CreateMaxFiles = 5

// fileTypes are the binary types, known by their magic bytes, in the order they are tried.
var fileTypes = []fileType{
	{
		MediaType: "image/png",
		Extension: ".png",
		Signatures: [][]signaturePart{
			{{Offset: 0, Bytes: []byte{0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a}}},
		},
	},
	{
		MediaType: "image/jpeg",
		Extension: ".jpg",
		Signatures: [][]signaturePart{
			{{Offset: 0, Bytes: []byte{0xff, 0xd8, 0xff}}},
		},
	},
	{
		MediaType: "image/gif",
		Extension: ".gif",
		Signatures: [][]signaturePart{
			{{Offset: 0, Bytes: []byte{0x47, 0x49, 0x46, 0x38, 0x37, 0x61}}},
			{{Offset: 0, Bytes: []byte{0x47, 0x49, 0x46, 0x38, 0x39, 0x61}}},
		},
	},
	{
		MediaType: "image/webp",
		Extension: ".webp",
		Signatures: [][]signaturePart{
			{{Offset: 0, Bytes: []byte{0x52, 0x49, 0x46, 0x46}}, {Offset: 8, Bytes: []byte{0x57, 0x45, 0x42, 0x50}}},
		},
	},
	{
		MediaType: "application/pdf",
		Extension: ".pdf",
		Signatures: [][]signaturePart{
			{{Offset: 0, Bytes: []byte{0x25, 0x50, 0x44, 0x46, 0x2d}}},
		},
	},
}

// textTypes are the types text is saved as; the first is the default.
var textTypes = []textType{
	{MediaType: "text/plain", Extension: ".txt"},
	{MediaType: "text/markdown", Extension: ".md"},
	{MediaType: "text/csv", Extension: ".csv"},
	{MediaType: "application/json", Extension: ".json"},
}

// textRefusedOpenings make text a program rather than a document.
var textRefusedOpenings = []string{
	"#!",
	"<!doctype",
	"<html",
	"<head",
	"<body",
	"<script",
	"<svg",
	"<?xml",
}
