// Code generated by packages/shared/scripts/emit-session-image.cjs from
// packages/shared/src/protocol/session-image.ts; DO NOT EDIT.

package domain

// ImageMaxBytes is the largest image a session takes.
const ImageMaxBytes = 5242880

// imageTypes is what counts as an image, in the order they are tried.
var imageTypes = []imageType{
	{
		MediaType: "image/png",
		Extension: ".png",
		Signatures: [][]imageSignaturePart{
			{{Offset: 0, Bytes: []byte{0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a}}},
		},
	},
	{
		MediaType: "image/jpeg",
		Extension: ".jpg",
		Signatures: [][]imageSignaturePart{
			{{Offset: 0, Bytes: []byte{0xff, 0xd8, 0xff}}},
		},
	},
	{
		MediaType: "image/gif",
		Extension: ".gif",
		Signatures: [][]imageSignaturePart{
			{{Offset: 0, Bytes: []byte{0x47, 0x49, 0x46, 0x38, 0x37, 0x61}}},
			{{Offset: 0, Bytes: []byte{0x47, 0x49, 0x46, 0x38, 0x39, 0x61}}},
		},
	},
	{
		MediaType: "image/webp",
		Extension: ".webp",
		Signatures: [][]imageSignaturePart{
			{{Offset: 0, Bytes: []byte{0x52, 0x49, 0x46, 0x46}}, {Offset: 8, Bytes: []byte{0x57, 0x45, 0x42, 0x50}}},
		},
	},
}
