export const TOKENS = {
  StorageService: Symbol.for('StorageService'),
  AnalyticsClient: Symbol.for('AnalyticsClient'),
  AnalyticsService: Symbol.for('AnalyticsService'),
  AdminUsersRepository: Symbol.for('AdminUsersRepository'),
  AdminUsersService: Symbol.for('AdminUsersService'),
  AuthClient: Symbol.for('AuthClient'),
  AuthRepository: Symbol.for('AuthRepository'),
  AuthStore: Symbol.for('AuthStore'),
  AuthService: Symbol.for('AuthService'),
  CapabilitiesRepository: Symbol.for('CapabilitiesRepository'),
  CapabilitiesService: Symbol.for('CapabilitiesService'),
  UserRepository: Symbol.for('UserRepository'),
  UsersService: Symbol.for('UsersService'),
  ApiTokensRepository: Symbol.for('ApiTokensRepository'),
  ApiTokensService: Symbol.for('ApiTokensService'),
  OrganizationsRepository: Symbol.for('OrganizationsRepository'),
  OrganizationsService: Symbol.for('OrganizationsService'),
  RolesRepository: Symbol.for('RolesRepository'),
  RolesService: Symbol.for('RolesService'),
  ProfileRepository: Symbol.for('ProfileRepository'),
  ProfileService: Symbol.for('ProfileService'),
} as const;
