export const AUTOMATION_REPOSITORY = Symbol('AUTOMATION_REPOSITORY');
export const AUTOMATION_RUN_REPOSITORY = Symbol('AUTOMATION_RUN_REPOSITORY');
export const AUTOMATION_SETTINGS_REPOSITORY = Symbol('AUTOMATION_SETTINGS_REPOSITORY');
