/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthPublicRouteImport } from './routes/_auth/_public'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthPublicForgotPasswordRouteImport } from './routes/_auth/_public/forgot-password'
import { Route as AuthPublicLoginRouteImport } from './routes/_auth/_public/login'
import { Route as AuthPublicRegisterRouteImport } from './routes/_auth/_public/register'
import { Route as AuthPublicResetPasswordRouteImport } from './routes/_auth/_public/reset-password'
import { Route as AuthOnboardingIndexRouteImport } from './routes/_auth/onboarding/index'
import { Route as AuthOnboardingGithubRouteImport } from './routes/_auth/onboarding/github'
import { Route as AuthOnboardingHostRouteImport } from './routes/_auth/onboarding/host'
import { Route as AuthOnboardingReadyRouteImport } from './routes/_auth/onboarding/ready'
import { Route as AuthOnboardingWorkspaceRouteImport } from './routes/_auth/onboarding/workspace'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations/index'
import { Route as AuthenticatedAutomationsAutomationIdRouteImport } from './routes/_authenticated/automations/$automationId'
import { Route as AuthenticatedAutomationsRunsRouteImport } from './routes/_authenticated/automations/runs'
import { Route as AuthenticatedPlanIndexRouteImport } from './routes/_authenticated/plan/index'
import { Route as AuthenticatedPlanCalendarRouteImport } from './routes/_authenticated/plan/calendar'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions/$sessionId'
import { Route as AuthenticatedSessionsNewRouteImport } from './routes/_authenticated/sessions/new'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedPlanCalendarGoogleRouteImport } from './routes/_authenticated/plan/calendar_.google'
import { Route as AuthenticatedSettingsHostsIndexRouteImport } from './routes/_authenticated/settings/hosts/index'
import { Route as AuthenticatedSettingsHostsNewRouteImport } from './routes/_authenticated/settings/hosts/new'
import { Route as AuthenticatedAutomationsAutomationIdSessionsSessionIdRouteImport } from './routes/_authenticated/automations_.$automationId.sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPublicRoute = AuthPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPublicForgotPasswordRoute =
  AuthPublicForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthPublicRoute,
  } as any)
const AuthPublicLoginRoute = AuthPublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthPublicRoute,
} as any)
const AuthPublicRegisterRoute = AuthPublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthPublicRoute,
} as any)
const AuthPublicResetPasswordRoute = AuthPublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthPublicRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingGithubRoute = AuthOnboardingGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingHostRoute = AuthOnboardingHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingReadyRoute = AuthOnboardingReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingWorkspaceRoute = AuthOnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdRoute =
  AuthenticatedAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsRunsRoute =
  AuthenticatedAutomationsRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedPlanIndexRoute = AuthenticatedPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanCalendarRoute =
  AuthenticatedPlanCalendarRouteImport.update({
    id: '/plan/calendar',
    path: '/plan/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsNewRoute =
  AuthenticatedSessionsNewRouteImport.update({
    id: '/sessions/new',
    path: '/sessions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPlanCalendarGoogleRoute =
  AuthenticatedPlanCalendarGoogleRouteImport.update({
    id: '/plan/calendar_/google',
    path: '/plan/calendar/google',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsHostsIndexRoute =
  AuthenticatedSettingsHostsIndexRouteImport.update({
    id: '/hosts/',
    path: '/hosts/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsHostsNewRoute =
  AuthenticatedSettingsHostsNewRouteImport.update({
    id: '/hosts/new',
    path: '/hosts/new',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute =
  AuthenticatedAutomationsAutomationIdSessionsSessionIdRouteImport.update({
    id: '/automations_/$automationId/sessions/$sessionId',
    path: '/automations/$automationId/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthOnboardingRouteWithChildren
  '/$': typeof AuthenticatedSplatRoute
  '/automations': typeof AuthenticatedAutomationsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/forgot-password': typeof AuthPublicForgotPasswordRoute
  '/login': typeof AuthPublicLoginRoute
  '/register': typeof AuthPublicRegisterRoute
  '/reset-password': typeof AuthPublicResetPasswordRoute
  '/onboarding/github': typeof AuthOnboardingGithubRoute
  '/onboarding/host': typeof AuthOnboardingHostRoute
  '/onboarding/ready': typeof AuthOnboardingReadyRoute
  '/onboarding/workspace': typeof AuthOnboardingWorkspaceRoute
  '/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRoute
  '/automations/runs': typeof AuthenticatedAutomationsRunsRoute
  '/plan/calendar': typeof AuthenticatedPlanCalendarRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/onboarding/': typeof AuthOnboardingIndexRoute
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/plan/': typeof AuthenticatedPlanIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/plan/calendar/google': typeof AuthenticatedPlanCalendarGoogleRoute
  '/settings/hosts/new': typeof AuthenticatedSettingsHostsNewRoute
  '/settings/hosts/': typeof AuthenticatedSettingsHostsIndexRoute
  '/automations/$automationId/sessions/$sessionId': typeof AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$': typeof AuthenticatedSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/forgot-password': typeof AuthPublicForgotPasswordRoute
  '/login': typeof AuthPublicLoginRoute
  '/register': typeof AuthPublicRegisterRoute
  '/reset-password': typeof AuthPublicResetPasswordRoute
  '/onboarding/github': typeof AuthOnboardingGithubRoute
  '/onboarding/host': typeof AuthOnboardingHostRoute
  '/onboarding/ready': typeof AuthOnboardingReadyRoute
  '/onboarding/workspace': typeof AuthOnboardingWorkspaceRoute
  '/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRoute
  '/automations/runs': typeof AuthenticatedAutomationsRunsRoute
  '/plan/calendar': typeof AuthenticatedPlanCalendarRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/onboarding': typeof AuthOnboardingIndexRoute
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/plan': typeof AuthenticatedPlanIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/plan/calendar/google': typeof AuthenticatedPlanCalendarGoogleRoute
  '/settings/hosts/new': typeof AuthenticatedSettingsHostsNewRoute
  '/settings/hosts': typeof AuthenticatedSettingsHostsIndexRoute
  '/automations/$automationId/sessions/$sessionId': typeof AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_auth/_public': typeof AuthPublicRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRouteWithChildren
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/_auth/_public/forgot-password': typeof AuthPublicForgotPasswordRoute
  '/_auth/_public/login': typeof AuthPublicLoginRoute
  '/_auth/_public/register': typeof AuthPublicRegisterRoute
  '/_auth/_public/reset-password': typeof AuthPublicResetPasswordRoute
  '/_auth/onboarding/github': typeof AuthOnboardingGithubRoute
  '/_auth/onboarding/host': typeof AuthOnboardingHostRoute
  '/_auth/onboarding/ready': typeof AuthOnboardingReadyRoute
  '/_auth/onboarding/workspace': typeof AuthOnboardingWorkspaceRoute
  '/_authenticated/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRoute
  '/_authenticated/automations/runs': typeof AuthenticatedAutomationsRunsRoute
  '/_authenticated/plan/calendar': typeof AuthenticatedPlanCalendarRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/_authenticated/plan/': typeof AuthenticatedPlanIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/plan/calendar_/google': typeof AuthenticatedPlanCalendarGoogleRoute
  '/_authenticated/settings/hosts/new': typeof AuthenticatedSettingsHostsNewRoute
  '/_authenticated/settings/hosts/': typeof AuthenticatedSettingsHostsIndexRoute
  '/_authenticated/automations_/$automationId/sessions/$sessionId': typeof AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/onboarding'
    | '/$'
    | '/automations'
    | '/settings'
    | '/oauth/consent'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/onboarding/github'
    | '/onboarding/host'
    | '/onboarding/ready'
    | '/onboarding/workspace'
    | '/automations/$automationId'
    | '/automations/runs'
    | '/plan/calendar'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/settings/profile'
    | '/onboarding/'
    | '/automations/'
    | '/plan/'
    | '/sessions/'
    | '/settings/'
    | '/plan/calendar/google'
    | '/settings/hosts/new'
    | '/settings/hosts/'
    | '/automations/$automationId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/$'
    | '/oauth/consent'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/onboarding/github'
    | '/onboarding/host'
    | '/onboarding/ready'
    | '/onboarding/workspace'
    | '/automations/$automationId'
    | '/automations/runs'
    | '/plan/calendar'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/settings/profile'
    | '/onboarding'
    | '/automations'
    | '/plan'
    | '/sessions'
    | '/settings'
    | '/plan/calendar/google'
    | '/settings/hosts/new'
    | '/settings/hosts'
    | '/automations/$automationId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/_auth/_public'
    | '/_auth/onboarding'
    | '/_authenticated/$'
    | '/_authenticated/automations'
    | '/_authenticated/settings'
    | '/oauth/consent'
    | '/_auth/_public/forgot-password'
    | '/_auth/_public/login'
    | '/_auth/_public/register'
    | '/_auth/_public/reset-password'
    | '/_auth/onboarding/github'
    | '/_auth/onboarding/host'
    | '/_auth/onboarding/ready'
    | '/_auth/onboarding/workspace'
    | '/_authenticated/automations/$automationId'
    | '/_authenticated/automations/runs'
    | '/_authenticated/plan/calendar'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/sessions/new'
    | '/_authenticated/settings/profile'
    | '/_auth/onboarding/'
    | '/_authenticated/automations/'
    | '/_authenticated/plan/'
    | '/_authenticated/sessions/'
    | '/_authenticated/settings/'
    | '/_authenticated/plan/calendar_/google'
    | '/_authenticated/settings/hosts/new'
    | '/_authenticated/settings/hosts/'
    | '/_authenticated/automations_/$automationId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_public': {
      id: '/_auth/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPublicRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_public/forgot-password': {
      id: '/_auth/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthPublicForgotPasswordRouteImport
      parentRoute: typeof AuthPublicRoute
    }
    '/_auth/_public/login': {
      id: '/_auth/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthPublicLoginRouteImport
      parentRoute: typeof AuthPublicRoute
    }
    '/_auth/_public/register': {
      id: '/_auth/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthPublicRegisterRouteImport
      parentRoute: typeof AuthPublicRoute
    }
    '/_auth/_public/reset-password': {
      id: '/_auth/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthPublicResetPasswordRouteImport
      parentRoute: typeof AuthPublicRoute
    }
    '/_auth/onboarding/': {
      id: '/_auth/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/github': {
      id: '/_auth/onboarding/github'
      path: '/github'
      fullPath: '/onboarding/github'
      preLoaderRoute: typeof AuthOnboardingGithubRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/host': {
      id: '/_auth/onboarding/host'
      path: '/host'
      fullPath: '/onboarding/host'
      preLoaderRoute: typeof AuthOnboardingHostRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/ready': {
      id: '/_auth/onboarding/ready'
      path: '/ready'
      fullPath: '/onboarding/ready'
      preLoaderRoute: typeof AuthOnboardingReadyRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/workspace': {
      id: '/_auth/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof AuthOnboardingWorkspaceRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/$automationId': {
      id: '/_authenticated/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/runs': {
      id: '/_authenticated/automations/runs'
      path: '/runs'
      fullPath: '/automations/runs'
      preLoaderRoute: typeof AuthenticatedAutomationsRunsRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/plan/': {
      id: '/_authenticated/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthenticatedPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan/calendar': {
      id: '/_authenticated/plan/calendar'
      path: '/plan/calendar'
      fullPath: '/plan/calendar'
      preLoaderRoute: typeof AuthenticatedPlanCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/new': {
      id: '/_authenticated/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedSessionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/plan/calendar_/google': {
      id: '/_authenticated/plan/calendar_/google'
      path: '/plan/calendar/google'
      fullPath: '/plan/calendar/google'
      preLoaderRoute: typeof AuthenticatedPlanCalendarGoogleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/hosts/': {
      id: '/_authenticated/settings/hosts/'
      path: '/hosts'
      fullPath: '/settings/hosts/'
      preLoaderRoute: typeof AuthenticatedSettingsHostsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/hosts/new': {
      id: '/_authenticated/settings/hosts/new'
      path: '/hosts/new'
      fullPath: '/settings/hosts/new'
      preLoaderRoute: typeof AuthenticatedSettingsHostsNewRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/automations_/$automationId/sessions/$sessionId': {
      id: '/_authenticated/automations_/$automationId/sessions/$sessionId'
      path: '/automations/$automationId/sessions/$sessionId'
      fullPath: '/automations/$automationId/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthPublicRouteChildren {
  AuthPublicForgotPasswordRoute: typeof AuthPublicForgotPasswordRoute
  AuthPublicLoginRoute: typeof AuthPublicLoginRoute
  AuthPublicRegisterRoute: typeof AuthPublicRegisterRoute
  AuthPublicResetPasswordRoute: typeof AuthPublicResetPasswordRoute
}

const AuthPublicRouteChildren: AuthPublicRouteChildren = {
  AuthPublicForgotPasswordRoute: AuthPublicForgotPasswordRoute,
  AuthPublicLoginRoute: AuthPublicLoginRoute,
  AuthPublicRegisterRoute: AuthPublicRegisterRoute,
  AuthPublicResetPasswordRoute: AuthPublicResetPasswordRoute,
}

const AuthPublicRouteWithChildren = AuthPublicRoute._addFileChildren(
  AuthPublicRouteChildren,
)

interface AuthOnboardingRouteChildren {
  AuthOnboardingGithubRoute: typeof AuthOnboardingGithubRoute
  AuthOnboardingHostRoute: typeof AuthOnboardingHostRoute
  AuthOnboardingReadyRoute: typeof AuthOnboardingReadyRoute
  AuthOnboardingWorkspaceRoute: typeof AuthOnboardingWorkspaceRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const AuthOnboardingRouteChildren: AuthOnboardingRouteChildren = {
  AuthOnboardingGithubRoute: AuthOnboardingGithubRoute,
  AuthOnboardingHostRoute: AuthOnboardingHostRoute,
  AuthOnboardingReadyRoute: AuthOnboardingReadyRoute,
  AuthOnboardingWorkspaceRoute: AuthOnboardingWorkspaceRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

const AuthOnboardingRouteWithChildren = AuthOnboardingRoute._addFileChildren(
  AuthOnboardingRouteChildren,
)

interface AuthRouteChildren {
  AuthPublicRoute: typeof AuthPublicRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPublicRoute: AuthPublicRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedAutomationsRouteChildren {
  AuthenticatedAutomationsAutomationIdRoute: typeof AuthenticatedAutomationsAutomationIdRoute
  AuthenticatedAutomationsRunsRoute: typeof AuthenticatedAutomationsRunsRoute
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
}

const AuthenticatedAutomationsRouteChildren: AuthenticatedAutomationsRouteChildren =
  {
    AuthenticatedAutomationsAutomationIdRoute:
      AuthenticatedAutomationsAutomationIdRoute,
    AuthenticatedAutomationsRunsRoute: AuthenticatedAutomationsRunsRoute,
    AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
  }

const AuthenticatedAutomationsRouteWithChildren =
  AuthenticatedAutomationsRoute._addFileChildren(
    AuthenticatedAutomationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsHostsNewRoute: typeof AuthenticatedSettingsHostsNewRoute
  AuthenticatedSettingsHostsIndexRoute: typeof AuthenticatedSettingsHostsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsHostsNewRoute: AuthenticatedSettingsHostsNewRoute,
  AuthenticatedSettingsHostsIndexRoute: AuthenticatedSettingsHostsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedPlanCalendarRoute: typeof AuthenticatedPlanCalendarRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedSessionsNewRoute: typeof AuthenticatedSessionsNewRoute
  AuthenticatedPlanIndexRoute: typeof AuthenticatedPlanIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedPlanCalendarGoogleRoute: typeof AuthenticatedPlanCalendarGoogleRoute
  AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute: typeof AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedPlanCalendarRoute: AuthenticatedPlanCalendarRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedSessionsNewRoute: AuthenticatedSessionsNewRoute,
  AuthenticatedPlanIndexRoute: AuthenticatedPlanIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedPlanCalendarGoogleRoute: AuthenticatedPlanCalendarGoogleRoute,
  AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute:
    AuthenticatedAutomationsAutomationIdSessionsSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
