import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * The whole schema, as one migration.
 *
 * Nothing had been deployed when the 51 migrations before this were squashed
 * into it, so no database has to be carried across: a fresh one gets this, and
 * a local one from before is dropped and recreated (`pnpm docker:dev` with an
 * empty volume). Why a table, key or index is the way it is was written in the
 * migration that introduced it; `git log -- apps/api/src/migrations` before
 * this file still has them, and the ORM entities repeat what a query relies on.
 *
 * Tables come in alphabetical order, each with its keys, checks and indexes;
 * the foreign keys follow once every table exists. The seed is the four global
 * system roles (mirroring `SYSTEM_ROLE_PERMISSIONS` in `@oppenheimer/shared`)
 * and the singleton `role_catalog_version` row.
 *
 * A change from here on is a new migration after this one, never an edit to it.
 */

/** `user.username`: lowercase letters and digits, single hyphens between them (`USERNAME_PATTERN`). */
export const USERNAME_CHECK = '^[a-z0-9](-?[a-z0-9])*$';

const EXTENSIONS = [
  `CREATE EXTENSION IF NOT EXISTS pg_trgm`,
  `CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`,
];

const TABLES: Record<string, string[]> = {
  access_grant: [
    `CREATE TABLE access_grant (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "principalType" character varying NOT NULL,
      "principalId" uuid NOT NULL,
      "resourceType" character varying NOT NULL,
      "resourceId" uuid,
      "grantedBy" uuid NOT NULL,
      "expiresAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_access_grant_principal_type" CHECK ("principalType" IN ('user', 'team', 'role'))
    )`,
    `ALTER TABLE access_grant ADD CONSTRAINT "PK_access_grant" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_access_grant_expiry" ON access_grant USING btree ("expiresAt") WHERE ("expiresAt" IS NOT NULL)`,
    `CREATE INDEX "IDX_access_grant_lookup" ON access_grant USING btree ("organizationId", "principalType", "principalId", "resourceType")`,
  ],
  account: [
    `CREATE TABLE account (
      id uuid NOT NULL,
      "userId" uuid NOT NULL,
      "accountId" character varying NOT NULL,
      "providerId" character varying NOT NULL,
      "accessToken" character varying,
      "refreshToken" character varying,
      "idToken" character varying,
      "accessTokenExpiresAt" timestamp with time zone,
      "refreshTokenExpiresAt" timestamp with time zone,
      scope character varying,
      password character varying,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE account ADD CONSTRAINT "PK_account" PRIMARY KEY (id)`,
    `ALTER TABLE account ADD CONSTRAINT "UQ_account_providerId_accountId" UNIQUE ("providerId", "accountId")`,
    `CREATE INDEX "IDX_account_userId" ON account USING btree ("userId")`,
  ],
  api_token: [
    `CREATE TABLE api_token (
      id uuid NOT NULL,
      "userId" uuid NOT NULL,
      name character varying(80) NOT NULL,
      prefix character varying(32) NOT NULL,
      "tokenHash" character varying(64) NOT NULL,
      scopes jsonb DEFAULT '[]'::jsonb NOT NULL,
      "organizationIds" jsonb,
      "ipAllowlist" jsonb,
      "expiresAt" timestamp with time zone,
      "lastUsedAt" timestamp with time zone,
      "revokedAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE api_token ADD CONSTRAINT "PK_api_token_id" PRIMARY KEY (id)`,
    `CREATE UNIQUE INDEX "IDX_api_token_tokenHash" ON api_token USING btree ("tokenHash")`,
    `CREATE INDEX "IDX_api_token_userId" ON api_token USING btree ("userId")`,
  ],
  automation: [
    `CREATE TABLE automation (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "projectId" uuid NOT NULL,
      "ownerUserId" uuid NOT NULL,
      name character varying(200) NOT NULL,
      "currentRevisionId" uuid NOT NULL,
      "pausedAt" timestamp with time zone,
      "pausedReason" character varying(32),
      "deletedAt" timestamp with time zone,
      overlap character varying(8),
      "maxRunsPerHour" integer,
      version integer DEFAULT 1 NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_automation_max_runs" CHECK (("maxRunsPerHour" >= 1)),
      CONSTRAINT "CHK_automation_name" CHECK ((char_length((name)::text) > 0)),
      CONSTRAINT "CHK_automation_overlap" CHECK (overlap IN ('skip', 'queue')),
      CONSTRAINT "CHK_automation_paused" CHECK ((("pausedAt" IS NULL) = ("pausedReason" IS NULL))),
      CONSTRAINT "CHK_automation_paused_reason" CHECK ("pausedReason" IN ('user', 'project_archived', 'host_unpaired', 'owner_lost_access')),
      CONSTRAINT "CHK_automation_version" CHECK ((version >= 1))
    )`,
    `ALTER TABLE automation ADD CONSTRAINT "PK_automation" PRIMARY KEY (id)`,
    `ALTER TABLE automation ADD CONSTRAINT "UQ_automation_organization_id" UNIQUE ("organizationId", id)`,
    `CREATE INDEX "IDX_automation_current_revision" ON automation USING btree ("currentRevisionId")`,
    `CREATE INDEX "IDX_automation_owner" ON automation USING btree ("ownerUserId")`,
    `CREATE INDEX "IDX_automation_project" ON automation USING btree ("organizationId", "projectId")`,
  ],
  automation_revision: [
    `CREATE TABLE automation_revision (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "automationId" uuid NOT NULL,
      number integer NOT NULL,
      "hostId" uuid NOT NULL,
      agent character varying(32) NOT NULL,
      model character varying(128),
      permission character varying(8) DEFAULT 'auto'::character varying NOT NULL,
      effort character varying(16),
      prompt text NOT NULL,
      repositories jsonb NOT NULL,
      "createdByUserId" uuid,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_automation_revision_number" CHECK ((number >= 1)),
      CONSTRAINT "CHK_automation_revision_permission" CHECK (permission IN ('auto', 'full')),
      CONSTRAINT "CHK_automation_revision_prompt" CHECK ((char_length(prompt) > 0)),
      CONSTRAINT "CHK_automation_revision_repositories" CHECK (((jsonb_typeof(repositories) = 'array'::text) AND (jsonb_array_length(repositories) >= 1)))
    )`,
    `ALTER TABLE automation_revision ADD CONSTRAINT "PK_automation_revision" PRIMARY KEY (id)`,
    `ALTER TABLE automation_revision ADD CONSTRAINT "UQ_automation_revision_automation_number" UNIQUE ("automationId", number)`,
    `ALTER TABLE automation_revision ADD CONSTRAINT "UQ_automation_revision_organization_id" UNIQUE ("organizationId", id)`,
    `CREATE INDEX "IDX_automation_revision_automation" ON automation_revision USING btree ("organizationId", "automationId")`,
    `CREATE INDEX "IDX_automation_revision_created_by" ON automation_revision USING btree ("createdByUserId") WHERE ("createdByUserId" IS NOT NULL)`,
    `CREATE INDEX "IDX_automation_revision_host" ON automation_revision USING btree ("hostId")`,
  ],
  automation_run: [
    `CREATE TABLE automation_run (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "automationId" uuid NOT NULL,
      "revisionId" uuid NOT NULL,
      "triggerId" uuid,
      cause character varying(16) NOT NULL,
      "causeKey" character varying(200) NOT NULL,
      "causeSummary" jsonb DEFAULT '{}'::jsonb NOT NULL,
      "inboundEventId" uuid,
      "scheduledFor" timestamp with time zone,
      outcome character varying(16) DEFAULT 'pending'::character varying NOT NULL,
      "skipReason" character varying(40),
      "availableAt" timestamp with time zone DEFAULT now() NOT NULL,
      attempts integer DEFAULT 0 NOT NULL,
      "sessionId" uuid,
      "requestedByUserId" uuid,
      "dispatchedAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_automation_run_attempts" CHECK ((attempts >= 0)),
      CONSTRAINT "CHK_automation_run_cause" CHECK (cause IN ('schedule', 'event', 'manual')),
      CONSTRAINT "CHK_automation_run_cause_summary" CHECK ((jsonb_typeof("causeSummary") = 'object'::text)),
      CONSTRAINT "CHK_automation_run_dispatched" CHECK ((((outcome)::text = 'dispatched'::text) = ("dispatchedAt" IS NOT NULL))),
      CONSTRAINT "CHK_automation_run_outcome" CHECK (outcome IN ('pending', 'skipped', 'expired', 'dispatched')),
      CONSTRAINT "CHK_automation_run_skip_reason" CHECK ((((outcome)::text = 'skipped'::text) = ("skipReason" IS NOT NULL)))
    )`,
    `ALTER TABLE automation_run ADD CONSTRAINT "PK_automation_run" PRIMARY KEY (id)`,
    `ALTER TABLE automation_run ADD CONSTRAINT "UQ_automation_run_automation_cause" UNIQUE ("automationId", "causeKey")`,
    `CREATE INDEX "IDX_automation_run_automation_created" ON automation_run USING btree ("organizationId", "automationId", "createdAt", id)`,
    `CREATE INDEX "IDX_automation_run_created_brin" ON automation_run USING brin ("createdAt")`,
    `CREATE INDEX "IDX_automation_run_dispatched" ON automation_run USING btree ("dispatchedAt") WHERE ((outcome)::text = 'dispatched'::text)`,
    `CREATE INDEX "IDX_automation_run_inbound_event" ON automation_run USING btree ("inboundEventId") WHERE ("inboundEventId" IS NOT NULL)`,
    `CREATE INDEX "IDX_automation_run_organization_created" ON automation_run USING btree ("organizationId", "createdAt", id)`,
    `CREATE INDEX "IDX_automation_run_organization_session" ON automation_run USING btree ("organizationId", "sessionId") WHERE ("sessionId" IS NOT NULL)`,
    `CREATE INDEX "IDX_automation_run_pending" ON automation_run USING btree ("availableAt") WHERE ((outcome)::text = 'pending'::text)`,
    `CREATE INDEX "IDX_automation_run_requested_by" ON automation_run USING btree ("requestedByUserId") WHERE ("requestedByUserId" IS NOT NULL)`,
    `CREATE INDEX "IDX_automation_run_revision" ON automation_run USING btree ("organizationId", "revisionId")`,
    `CREATE INDEX "IDX_automation_run_trigger" ON automation_run USING btree ("triggerId") WHERE ("triggerId" IS NOT NULL)`,
    `CREATE UNIQUE INDEX "UQ_automation_run_session" ON automation_run USING btree ("sessionId") WHERE ("sessionId" IS NOT NULL)`,
  ],
  automation_settings: [
    `CREATE TABLE automation_settings (
      "organizationId" uuid NOT NULL,
      "maxRunsPerAutomationHour" integer,
      "maxRunsPerWorkspaceHour" integer,
      "liveRunsPerHost" integer,
      overlap character varying(8),
      "staleTtlSeconds" integer,
      "missedGraceSeconds" integer,
      "maxRunSeconds" integer,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_automation_settings_overlap" CHECK (overlap IN ('skip', 'queue')),
      CONSTRAINT "CHK_automation_settings_positive" CHECK (((COALESCE("maxRunsPerAutomationHour", 1) >= 1) AND (COALESCE("maxRunsPerWorkspaceHour", 1) >= 1) AND (COALESCE("liveRunsPerHost", 1) >= 1) AND (COALESCE("staleTtlSeconds", 60) >= 60) AND (COALESCE("missedGraceSeconds", 0) >= 0) AND (COALESCE("maxRunSeconds", 60) >= 60)))
    )`,
    `ALTER TABLE automation_settings ADD CONSTRAINT "PK_automation_settings" PRIMARY KEY ("organizationId")`,
  ],
  automation_trigger: [
    `CREATE TABLE automation_trigger (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "automationId" uuid NOT NULL,
      "position" smallint DEFAULT 0 NOT NULL,
      source character varying(32) NOT NULL,
      "eventType" character varying(64) NOT NULL,
      config jsonb NOT NULL,
      timezone character varying(64),
      "nextFireAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_automation_trigger_config" CHECK ((jsonb_typeof(config) = 'object'::text)),
      CONSTRAINT "CHK_automation_trigger_next_fire" CHECK ((((source)::text = 'schedule'::text) OR ("nextFireAt" IS NULL))),
      CONSTRAINT "CHK_automation_trigger_position" CHECK (("position" >= 0)),
      CONSTRAINT "CHK_automation_trigger_schedule" CHECK ((((source)::text = 'schedule'::text) = (timezone IS NOT NULL))),
      CONSTRAINT "CHK_automation_trigger_source" CHECK (source IN ('schedule', 'github'))
    )`,
    `ALTER TABLE automation_trigger ADD CONSTRAINT "PK_automation_trigger" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_automation_trigger_automation" ON automation_trigger USING btree ("automationId", "organizationId", "position")`,
    `CREATE INDEX "IDX_automation_trigger_due" ON automation_trigger USING btree ("nextFireAt") WHERE ("nextFireAt" IS NOT NULL)`,
    `CREATE INDEX "IDX_automation_trigger_match" ON automation_trigger USING btree ("organizationId", source, "eventType")`,
  ],
  automation_trigger_subject: [
    `CREATE TABLE automation_trigger_subject (
      "triggerId" uuid NOT NULL,
      "organizationId" uuid NOT NULL,
      "subjectKind" character varying(32) NOT NULL,
      "subjectRef" character varying(128) NOT NULL,
      CONSTRAINT "CHK_automation_trigger_subject_kind" CHECK ((("subjectKind")::text = 'repository'::text))
    )`,
    `ALTER TABLE automation_trigger_subject ADD CONSTRAINT "PK_automation_trigger_subject" PRIMARY KEY ("triggerId", "subjectKind", "subjectRef")`,
    `CREATE INDEX "IDX_automation_trigger_subject_lookup" ON automation_trigger_subject USING btree ("organizationId", "subjectKind", "subjectRef")`,
  ],
  feature_flag: [
    `CREATE TABLE feature_flag (
      id uuid NOT NULL,
      key character varying(64) NOT NULL,
      enabled boolean DEFAULT false NOT NULL,
      rules jsonb DEFAULT '[]'::jsonb NOT NULL,
      fallthrough jsonb NOT NULL,
      salt character varying(32) NOT NULL,
      "updatedBy" uuid,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE feature_flag ADD CONSTRAINT "PK_feature_flag" PRIMARY KEY (id)`,
    `ALTER TABLE feature_flag ADD CONSTRAINT "UQ_feature_flag_key" UNIQUE (key)`,
  ],
  feature_flag_change: [
    `CREATE TABLE feature_flag_change (
      id uuid NOT NULL,
      "subjectType" character varying(16) NOT NULL,
      "subjectKey" character varying(64) NOT NULL,
      action character varying(32) NOT NULL,
      "actorId" uuid,
      comment character varying(500),
      before jsonb,
      after jsonb,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_feature_flag_change_action" CHECK (action IN ('targeting_updated', 'toggled', 'segment_created', 'segment_updated', 'segment_deleted')),
      CONSTRAINT "CHK_feature_flag_change_subject_type" CHECK ("subjectType" IN ('flag', 'segment'))
    )`,
    `ALTER TABLE feature_flag_change ADD CONSTRAINT "PK_feature_flag_change" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_feature_flag_change_created" ON feature_flag_change USING btree ("createdAt")`,
    `CREATE INDEX "IDX_feature_flag_change_subject" ON feature_flag_change USING btree ("subjectType", "subjectKey", "createdAt")`,
  ],
  feature_flag_segment: [
    `CREATE TABLE feature_flag_segment (
      id uuid NOT NULL,
      key character varying(64) NOT NULL,
      name character varying(100) NOT NULL,
      description character varying(255),
      conditions jsonb DEFAULT '[]'::jsonb NOT NULL,
      "updatedBy" uuid,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE feature_flag_segment ADD CONSTRAINT "PK_feature_flag_segment" PRIMARY KEY (id)`,
    `ALTER TABLE feature_flag_segment ADD CONSTRAINT "UQ_feature_flag_segment_key" UNIQUE (key)`,
  ],
  github_installation: [
    `CREATE TABLE github_installation (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "githubInstallationId" bigint NOT NULL,
      "accountLogin" character varying NOT NULL,
      "accountType" character varying NOT NULL,
      "repositorySelection" character varying NOT NULL,
      "installedByUserId" uuid NOT NULL,
      "suspendedAt" timestamp with time zone,
      "deletedAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      "statusChangedAt" timestamp with time zone,
      CONSTRAINT "CHK_github_installation_account_type" CHECK ("accountType" IN ('User', 'Organization')),
      CONSTRAINT "CHK_github_installation_repository_selection" CHECK ("repositorySelection" IN ('all', 'selected'))
    )`,
    `ALTER TABLE github_installation ADD CONSTRAINT "PK_github_installation" PRIMARY KEY (id)`,
    `ALTER TABLE github_installation ADD CONSTRAINT "UQ_github_installation_organization_id" UNIQUE ("organizationId", id)`,
    `CREATE INDEX "IDX_github_installation_installed_by" ON github_installation USING btree ("installedByUserId")`,
    `CREATE INDEX "IDX_github_installation_organization" ON github_installation USING btree ("organizationId")`,
    `CREATE UNIQUE INDEX "UQ_github_installation_live_github_id" ON github_installation USING btree ("githubInstallationId") WHERE ("deletedAt" IS NULL)`,
  ],
  host: [
    `CREATE TABLE host (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "ownerUserId" uuid NOT NULL,
      name character varying(80) NOT NULL,
      hostname character varying(255),
      os character varying(40),
      arch character varying(40),
      "runnerVersion" character varying(40),
      capabilities jsonb,
      "publicKey" text NOT NULL,
      "publicKeyFingerprint" character varying(64) NOT NULL,
      "lastSeenAt" timestamp with time zone,
      "unpairedAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE host ADD CONSTRAINT "PK_host" PRIMARY KEY (id)`,
    `ALTER TABLE host ADD CONSTRAINT "UQ_host_public_key_fingerprint" UNIQUE ("publicKeyFingerprint")`,
    `CREATE INDEX "IDX_host_owner" ON host USING btree ("ownerUserId")`,
  ],
  host_event: [
    `CREATE TABLE host_event (
      id bigint NOT NULL,
      "hostId" uuid NOT NULL,
      kind character varying(32) NOT NULL,
      payload jsonb DEFAULT '{}'::jsonb NOT NULL,
      "occurredAt" timestamp with time zone DEFAULT now() NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_host_event_kind" CHECK (kind IN ('paired', 'renamed', 'unpaired', 'facts_changed', 'network_changed', 'runner_updated', 'runner_rolled_back')),
      CONSTRAINT "CHK_host_event_payload_object" CHECK ((jsonb_typeof(payload) = 'object'::text))
    )`,
    `ALTER TABLE host_event ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
      SEQUENCE NAME host_event_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1
    )`,
    `ALTER TABLE host_event ADD CONSTRAINT "PK_host_event" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_host_event_host_occurred" ON host_event USING btree ("hostId", "occurredAt", id)`,
    `CREATE INDEX "IDX_host_event_occurred_brin" ON host_event USING brin ("occurredAt")`,
  ],
  host_inventory: [
    `CREATE TABLE host_inventory (
      "hostId" uuid NOT NULL,
      "factsHash" character varying(64) NOT NULL,
      platform character varying(16) NOT NULL,
      "osName" character varying(80),
      "osVersion" character varying(40),
      "kernelVersion" character varying(64),
      arch character varying(16) NOT NULL,
      hostname character varying(255) NOT NULL,
      "cpuModel" character varying(128),
      "cpuCount" smallint,
      "memoryTotalBytes" bigint,
      "diskTotalBytes" bigint,
      virtualization character varying(24),
      "cloudProvider" character varying(24),
      timezone character varying(64),
      "bootedAt" timestamp with time zone,
      "runnerVersion" character varying(40) NOT NULL,
      channel character varying(16),
      "serviceManager" character varying(16),
      tools jsonb DEFAULT '[]'::jsonb NOT NULL,
      facts jsonb NOT NULL,
      "changedAt" timestamp with time zone DEFAULT now() NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_host_inventory_cpu_count" CHECK ((("cpuCount" IS NULL) OR ("cpuCount" > 0))),
      CONSTRAINT "CHK_host_inventory_disk" CHECK ((("diskTotalBytes" IS NULL) OR ("diskTotalBytes" > 0))),
      CONSTRAINT "CHK_host_inventory_facts_hash" CHECK ((("factsHash")::text ~ '^[0-9a-f]{64}$'::text)),
      CONSTRAINT "CHK_host_inventory_memory" CHECK ((("memoryTotalBytes" IS NULL) OR ("memoryTotalBytes" > 0))),
      CONSTRAINT "CHK_host_inventory_platform" CHECK (platform IN ('macos', 'debian', 'ubuntu', 'linux', 'unsupported')),
      CONSTRAINT "CHK_host_inventory_tools_array" CHECK ((jsonb_typeof(tools) = 'array'::text))
    )`,
    `ALTER TABLE host_inventory ADD CONSTRAINT "PK_host_inventory" PRIMARY KEY ("hostId")`,
  ],
  host_network: [
    `CREATE TABLE host_network (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "hostId" uuid NOT NULL,
      ip inet NOT NULL,
      "countryCode" character(2),
      region character varying(64),
      city character varying(64),
      asn integer,
      "asnOrg" character varying(128),
      "firstSeenAt" timestamp with time zone DEFAULT now() NOT NULL,
      "lastSeenAt" timestamp with time zone DEFAULT now() NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_host_network_asn" CHECK (((asn IS NULL) OR (asn > 0))),
      CONSTRAINT "CHK_host_network_country" CHECK (("countryCode" ~ '^[A-Z]{2}$'::text)),
      CONSTRAINT "CHK_host_network_seen_order" CHECK (("lastSeenAt" >= "firstSeenAt"))
    )`,
    `ALTER TABLE host_network ADD CONSTRAINT "PK_host_network" PRIMARY KEY (id)`,
    `ALTER TABLE host_network ADD CONSTRAINT "UQ_host_network_host_ip" UNIQUE ("hostId", ip)`,
    `CREATE INDEX "IDX_host_network_last_seen" ON host_network USING btree ("lastSeenAt")`,
  ],
  host_pairing_token: [
    `CREATE TABLE host_pairing_token (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "ownerUserId" uuid NOT NULL,
      "intendedName" character varying(80) NOT NULL,
      prefix character varying(32) NOT NULL,
      "tokenHash" character varying(64) NOT NULL,
      "createdFromIp" inet,
      "redeemedFromIp" inet,
      "expiresAt" timestamp with time zone NOT NULL,
      "revokedAt" timestamp with time zone,
      "redeemedAt" timestamp with time zone,
      "redeemedHostId" uuid,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_host_pairing_token_redemption" CHECK ((("redeemedAt" IS NULL) = ("redeemedHostId" IS NULL)))
    )`,
    `ALTER TABLE host_pairing_token ADD CONSTRAINT "PK_host_pairing_token" PRIMARY KEY (id)`,
    `ALTER TABLE host_pairing_token ADD CONSTRAINT "UQ_host_pairing_token_hash" UNIQUE ("tokenHash")`,
    `CREATE INDEX "IDX_host_pairing_token_owner" ON host_pairing_token USING btree ("ownerUserId")`,
    `CREATE INDEX "IDX_host_pairing_token_redeemed_host" ON host_pairing_token USING btree ("redeemedHostId") WHERE ("redeemedHostId" IS NOT NULL)`,
  ],
  host_presence: [
    `CREATE TABLE host_presence (
      "hostId" uuid NOT NULL,
      "currentNetworkId" uuid,
      "connectedAt" timestamp with time zone,
      "lastSeenAt" timestamp with time zone NOT NULL,
      "roundTripMillis" integer,
      "loadAverage" numeric(7,2),
      "memoryAvailableBytes" bigint,
      "diskFreeBytes" bigint,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_host_presence_disk" CHECK ((("diskFreeBytes" IS NULL) OR ("diskFreeBytes" >= 0))),
      CONSTRAINT "CHK_host_presence_load" CHECK ((("loadAverage" IS NULL) OR ("loadAverage" >= (0)::numeric))),
      CONSTRAINT "CHK_host_presence_memory" CHECK ((("memoryAvailableBytes" IS NULL) OR ("memoryAvailableBytes" >= 0))),
      CONSTRAINT "CHK_host_presence_round_trip" CHECK ((("roundTripMillis" IS NULL) OR ("roundTripMillis" >= 0)))
    )
    WITH (fillfactor='70')`,
    `ALTER TABLE host_presence ADD CONSTRAINT "PK_host_presence" PRIMARY KEY ("hostId")`,
    `CREATE INDEX "IDX_host_presence_current_network" ON host_presence USING btree ("currentNetworkId") WHERE ("currentNetworkId" IS NOT NULL)`,
  ],
  inbound_delivery: [
    `CREATE TABLE inbound_delivery (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      source character varying(32) NOT NULL,
      "deliveryId" character varying(128) NOT NULL,
      "eventName" character varying(64) NOT NULL,
      payload jsonb NOT NULL,
      status character varying(16) DEFAULT 'received'::character varying NOT NULL,
      "eventCount" integer DEFAULT 0 NOT NULL,
      "lastError" text,
      "receivedAt" timestamp with time zone DEFAULT now() NOT NULL,
      "processedAt" timestamp with time zone,
      "restagedAt" timestamp with time zone,
      "payloadDigest" character varying(64),
      CONSTRAINT "CHK_inbound_delivery_event_count" CHECK (("eventCount" >= 0)),
      CONSTRAINT "CHK_inbound_delivery_payload" CHECK ((jsonb_typeof(payload) = 'object'::text)),
      CONSTRAINT "CHK_inbound_delivery_source" CHECK (((source)::text = 'github'::text)),
      CONSTRAINT "CHK_inbound_delivery_status" CHECK (status IN ('received', 'processed', 'failed'))
    )`,
    `ALTER TABLE inbound_delivery ADD CONSTRAINT "PK_inbound_delivery" PRIMARY KEY (id)`,
    `ALTER TABLE inbound_delivery ADD CONSTRAINT "UQ_inbound_delivery_source_delivery" UNIQUE (source, "deliveryId")`,
    `CREATE INDEX "IDX_inbound_delivery_received_brin" ON inbound_delivery USING brin ("receivedAt")`,
    `CREATE INDEX "IDX_inbound_delivery_unprocessed" ON inbound_delivery USING btree ("receivedAt") WHERE ((status)::text = 'received'::text)`,
    `CREATE UNIQUE INDEX "UQ_inbound_delivery_source_payload" ON inbound_delivery USING btree (source, "payloadDigest") WHERE ("payloadDigest" IS NOT NULL)`,
  ],
  inbound_event: [
    `CREATE TABLE inbound_event (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "inboundDeliveryId" uuid,
      source character varying(32) NOT NULL,
      "externalId" character varying(200) NOT NULL,
      "eventType" character varying(64) NOT NULL,
      "subjectKind" character varying(32) NOT NULL,
      "subjectRef" character varying(128) NOT NULL,
      "actorLogin" character varying(255),
      "actorIsOwnApp" boolean DEFAULT false NOT NULL,
      attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
      context jsonb DEFAULT '{}'::jsonb NOT NULL,
      "schemaVersion" smallint DEFAULT 1 NOT NULL,
      "occurredAt" timestamp with time zone NOT NULL,
      "receivedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_inbound_event_attributes" CHECK ((jsonb_typeof(attributes) = 'object'::text)),
      CONSTRAINT "CHK_inbound_event_context" CHECK ((jsonb_typeof(context) = 'object'::text)),
      CONSTRAINT "CHK_inbound_event_schema_version" CHECK (("schemaVersion" >= 1)),
      CONSTRAINT "CHK_inbound_event_source" CHECK (((source)::text = 'github'::text))
    )`,
    `ALTER TABLE inbound_event ADD CONSTRAINT "PK_inbound_event" PRIMARY KEY (id)`,
    `ALTER TABLE inbound_event ADD CONSTRAINT "UQ_inbound_event_organization_external" UNIQUE ("organizationId", source, "externalId")`,
    `ALTER TABLE inbound_event ADD CONSTRAINT "UQ_inbound_event_organization_id" UNIQUE ("organizationId", id)`,
    `CREATE INDEX "IDX_inbound_event_delivery" ON inbound_event USING btree ("inboundDeliveryId")`,
    `CREATE INDEX "IDX_inbound_event_preview" ON inbound_event USING btree ("organizationId", source, "eventType", "subjectRef", "occurredAt")`,
    `CREATE INDEX "IDX_inbound_event_received_brin" ON inbound_event USING brin ("receivedAt")`,
  ],
  invitation: [
    `CREATE TABLE invitation (
      id uuid NOT NULL,
      "organizationId" uuid NOT NULL,
      email character varying NOT NULL,
      role character varying,
      status character varying DEFAULT 'pending'::character varying NOT NULL,
      "teamId" uuid,
      "inviterId" uuid NOT NULL,
      "expiresAt" timestamp with time zone NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE invitation ADD CONSTRAINT "PK_invitation_id" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_invitation_email" ON invitation USING btree (email)`,
    `CREATE INDEX "IDX_invitation_inviterId" ON invitation USING btree ("inviterId")`,
    `CREATE INDEX "IDX_invitation_organizationId" ON invitation USING btree ("organizationId")`,
    `CREATE INDEX "IDX_invitation_teamId" ON invitation USING btree ("teamId") WHERE ("teamId" IS NOT NULL)`,
  ],
  member: [
    `CREATE TABLE member (
      id uuid NOT NULL,
      "organizationId" uuid NOT NULL,
      "userId" uuid NOT NULL,
      role character varying DEFAULT 'member'::character varying NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE member ADD CONSTRAINT "PK_member_id" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_member_organizationId" ON member USING btree ("organizationId")`,
    `CREATE INDEX "IDX_member_userId" ON member USING btree ("userId")`,
  ],
  oauthAccessToken: [
    `CREATE TABLE "oauthAccessToken" (
      id uuid NOT NULL,
      "accessToken" character varying,
      "refreshToken" character varying,
      "accessTokenExpiresAt" timestamp with time zone,
      "refreshTokenExpiresAt" timestamp with time zone,
      "clientId" character varying NOT NULL,
      "userId" uuid,
      scopes text NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE "oauthAccessToken" ADD CONSTRAINT "PK_oauthAccessToken_id" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_oauthAccessToken_accessToken" ON "oauthAccessToken" USING btree ("accessToken")`,
    `CREATE INDEX "IDX_oauthAccessToken_clientId" ON "oauthAccessToken" USING btree ("clientId")`,
    `CREATE INDEX "IDX_oauthAccessToken_userId" ON "oauthAccessToken" USING btree ("userId")`,
  ],
  oauthApplication: [
    `CREATE TABLE "oauthApplication" (
      id uuid NOT NULL,
      name character varying,
      icon text,
      metadata text,
      "clientId" character varying NOT NULL,
      "clientSecret" character varying,
      "redirectURLs" text NOT NULL,
      type character varying NOT NULL,
      disabled boolean DEFAULT false NOT NULL,
      "userId" character varying,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE "oauthApplication" ADD CONSTRAINT "PK_oauthApplication_id" PRIMARY KEY (id)`,
    `ALTER TABLE "oauthApplication" ADD CONSTRAINT "UQ_oauthApplication_clientId" UNIQUE ("clientId")`,
  ],
  oauthConsent: [
    `CREATE TABLE "oauthConsent" (
      id uuid NOT NULL,
      "clientId" character varying NOT NULL,
      "userId" uuid NOT NULL,
      scopes text NOT NULL,
      "consentGiven" boolean DEFAULT false NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE "oauthConsent" ADD CONSTRAINT "PK_oauthConsent_id" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_oauthConsent_clientId" ON "oauthConsent" USING btree ("clientId")`,
    `CREATE INDEX "IDX_oauthConsent_userId" ON "oauthConsent" USING btree ("userId")`,
  ],
  organization: [
    `CREATE TABLE organization (
      id uuid NOT NULL,
      name character varying NOT NULL,
      slug character varying NOT NULL,
      logo character varying,
      metadata text,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "roleVersion" integer DEFAULT 1 NOT NULL
    )`,
    `ALTER TABLE organization ADD CONSTRAINT "PK_organization_id" PRIMARY KEY (id)`,
    `ALTER TABLE organization ADD CONSTRAINT "UQ_organization_slug" UNIQUE (slug)`,
  ],
  outbox_message: [
    `CREATE TABLE outbox_message (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      channel character varying(16) DEFAULT 'event'::character varying NOT NULL,
      topic character varying,
      "eventName" character varying NOT NULL,
      "aggregateId" character varying,
      payload jsonb NOT NULL,
      reason text NOT NULL,
      status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
      attempts integer DEFAULT 0 NOT NULL,
      "availableAt" timestamp with time zone DEFAULT now() NOT NULL,
      "lockedBy" character varying,
      "lockedUntil" timestamp with time zone,
      "lastError" text,
      "correlationId" character varying,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "processedAt" timestamp with time zone
    )`,
    `ALTER TABLE outbox_message ADD CONSTRAINT "PK_outbox_message" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_outbox_message_created_brin" ON outbox_message USING brin ("createdAt")`,
    `CREATE INDEX "IDX_outbox_message_pending" ON outbox_message USING btree ("createdAt") WHERE ((status)::text = 'pending'::text)`,
  ],
  project: [
    `CREATE TABLE project (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      name character varying NOT NULL,
      slug character varying NOT NULL,
      "archivedAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      "defaultHostId" uuid,
      "defaultAgent" character varying,
      "createdByUserId" uuid,
      "isUnassigned" boolean DEFAULT false NOT NULL
    )`,
    `ALTER TABLE project ADD CONSTRAINT "PK_project" PRIMARY KEY (id)`,
    `ALTER TABLE project ADD CONSTRAINT "UQ_project_organization_id" UNIQUE ("organizationId", id)`,
    `ALTER TABLE project ADD CONSTRAINT "UQ_project_organization_slug" UNIQUE ("organizationId", slug)`,
    `CREATE INDEX "IDX_project_created_by" ON project USING btree ("createdByUserId") WHERE ("createdByUserId" IS NOT NULL)`,
    `CREATE INDEX "IDX_project_default_host" ON project USING btree ("defaultHostId")`,
    `CREATE INDEX "IDX_project_organization" ON project USING btree ("organizationId")`,
    `CREATE UNIQUE INDEX "UQ_project_organization_unassigned" ON project USING btree ("organizationId") WHERE "isUnassigned"`,
  ],
  project_repository: [
    `CREATE TABLE project_repository (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "projectId" uuid NOT NULL,
      "installationId" uuid NOT NULL,
      "githubRepoId" bigint NOT NULL,
      "repositoryFullName" character varying NOT NULL,
      "isDefault" boolean NOT NULL,
      "baseBranch" character varying NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "organizationId" uuid NOT NULL,
      "position" smallint NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE project_repository ADD CONSTRAINT "PK_project_repository" PRIMARY KEY (id)`,
    `ALTER TABLE project_repository ADD CONSTRAINT "UQ_project_repository_project_repo" UNIQUE ("projectId", "githubRepoId")`,
    `CREATE INDEX "IDX_project_repository_installation" ON project_repository USING btree ("organizationId", "installationId")`,
    `CREATE INDEX "IDX_project_repository_organization_repo" ON project_repository USING btree ("organizationId", "githubRepoId")`,
  ],
  rateLimit: [
    `CREATE TABLE "rateLimit" (
      id uuid NOT NULL,
      key character varying,
      count integer,
      "lastRequest" bigint
    )`,
    `ALTER TABLE "rateLimit" ADD CONSTRAINT "PK_rateLimit_id" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_rateLimit_key" ON "rateLimit" USING btree (key)`,
  ],
  role: [
    `CREATE TABLE role (
      id uuid NOT NULL,
      name character varying NOT NULL,
      description character varying,
      "isSystem" boolean DEFAULT false NOT NULL,
      permissions jsonb DEFAULT '[]'::jsonb NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      "organizationId" uuid
    )`,
    `ALTER TABLE role ADD CONSTRAINT "PK_role_id" PRIMARY KEY (id)`,
    `CREATE UNIQUE INDEX "UQ_role_global_name" ON role USING btree (name) WHERE ("organizationId" IS NULL)`,
    `CREATE UNIQUE INDEX "UQ_role_org_name" ON role USING btree ("organizationId", name) WHERE ("organizationId" IS NOT NULL)`,
  ],
  role_catalog_version: [
    `CREATE TABLE role_catalog_version (
      id smallint DEFAULT 1 NOT NULL,
      version bigint DEFAULT 1 NOT NULL,
      CONSTRAINT "CHK_role_catalog_version_singleton" CHECK ((id = 1))
    )`,
    `ALTER TABLE role_catalog_version ADD CONSTRAINT "PK_role_catalog_version" PRIMARY KEY (id)`,
  ],
  session: [
    `CREATE TABLE session (
      id uuid NOT NULL,
      "userId" uuid NOT NULL,
      token character varying NOT NULL,
      "expiresAt" timestamp with time zone NOT NULL,
      "ipAddress" character varying,
      "userAgent" character varying,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      "impersonatedBy" uuid,
      "activeOrganizationId" uuid,
      "activeTeamId" uuid,
      delegated boolean DEFAULT false NOT NULL,
      "delegatedCredentialId" character varying
    )`,
    `ALTER TABLE session ADD CONSTRAINT "PK_session" PRIMARY KEY (id)`,
    `ALTER TABLE session ADD CONSTRAINT "UQ_session_token" UNIQUE (token)`,
    `CREATE INDEX "IDX_session_activeOrganizationId" ON session USING btree ("activeOrganizationId") WHERE ("activeOrganizationId" IS NOT NULL)`,
    `CREATE INDEX "IDX_session_activeTeamId" ON session USING btree ("activeTeamId") WHERE ("activeTeamId" IS NOT NULL)`,
    `CREATE INDEX "IDX_session_impersonatedBy" ON session USING btree ("impersonatedBy") WHERE ("impersonatedBy" IS NOT NULL)`,
    `CREATE INDEX "IDX_session_userId" ON session USING btree ("userId")`,
  ],
  session_checkout: [
    `CREATE TABLE session_checkout (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "sessionId" uuid NOT NULL,
      "installationId" uuid NOT NULL,
      "githubRepoId" bigint NOT NULL,
      "repositoryFullName" character varying NOT NULL,
      "storeDirectoryName" character varying,
      "directoryName" character varying NOT NULL,
      mode character varying DEFAULT 'worktree'::character varying NOT NULL,
      "baseBranch" character varying NOT NULL,
      branch character varying NOT NULL,
      "worktreeCreatedAt" timestamp with time zone,
      "pushedAt" timestamp with time zone,
      "removedAt" timestamp with time zone,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_session_checkout_mode" CHECK (mode IN ('worktree', 'clone'))
    )`,
    `ALTER TABLE session_checkout ADD CONSTRAINT "PK_session_checkout" PRIMARY KEY (id)`,
    `ALTER TABLE session_checkout ADD CONSTRAINT "UQ_session_checkout_session_directory" UNIQUE ("sessionId", "directoryName")`,
    `ALTER TABLE session_checkout ADD CONSTRAINT "UQ_session_checkout_session_id" UNIQUE ("sessionId", id)`,
    `CREATE INDEX "IDX_session_checkout_installation" ON session_checkout USING btree ("organizationId", "installationId")`,
    `CREATE UNIQUE INDEX "UQ_session_checkout_session_repo" ON session_checkout USING btree ("sessionId", "githubRepoId") WHERE ("removedAt" IS NULL)`,
  ],
  session_turn: [
    `CREATE TABLE session_turn (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "sessionId" uuid NOT NULL,
      seq integer NOT NULL,
      origin character varying(16) NOT NULL,
      drive character varying(16) DEFAULT 'interactive'::character varying NOT NULL,
      state character varying(20) DEFAULT 'queued'::character varying NOT NULL,
      prompt text,
      "observedWorking" boolean DEFAULT false NOT NULL,
      "startedAt" timestamp with time zone,
      "endedAt" timestamp with time zone,
      "exitCode" integer,
      "agentSessionId" character varying(128),
      result text,
      "failureDetail" text,
      "costUsd" numeric(12,6),
      "permissionDenials" integer DEFAULT 0 NOT NULL,
      "outputRef" character varying(512),
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_session_turn_cost" CHECK ((("costUsd" IS NULL) OR ("costUsd" >= (0)::numeric))),
      CONSTRAINT "CHK_session_turn_denials" CHECK (("permissionDenials" >= 0)),
      CONSTRAINT "CHK_session_turn_drive" CHECK (drive IN ('interactive', 'headless')),
      CONSTRAINT "CHK_session_turn_ended" CHECK ((("endedAt" IS NULL) OR ("startedAt" IS NULL) OR ("endedAt" >= "startedAt"))),
      CONSTRAINT "CHK_session_turn_origin" CHECK (origin IN ('person', 'automation', 'follow_up')),
      CONSTRAINT "CHK_session_turn_seq" CHECK ((seq >= 1)),
      CONSTRAINT "CHK_session_turn_state" CHECK (state IN ('queued', 'in_progress', 'requires_action', 'completed', 'failed', 'cancelled', 'expired'))
    )`,
    `ALTER TABLE session_turn ADD CONSTRAINT "PK_session_turn" PRIMARY KEY (id)`,
    `ALTER TABLE session_turn ADD CONSTRAINT "UQ_session_turn_session_seq" UNIQUE ("sessionId", seq)`,
    `CREATE INDEX "IDX_session_turn_live" ON session_turn USING btree ("sessionId") WHERE (state IN ('queued', 'in_progress', 'requires_action'))`,
    `CREATE INDEX "IDX_session_turn_organization_session" ON session_turn USING btree ("organizationId", "sessionId")`,
  ],
  team: [
    `CREATE TABLE team (
      id uuid NOT NULL,
      name character varying NOT NULL,
      "organizationId" uuid NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone
    )`,
    `ALTER TABLE team ADD CONSTRAINT "PK_team_id" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_team_organizationId" ON team USING btree ("organizationId")`,
  ],
  teamMember: [
    `CREATE TABLE "teamMember" (
      id uuid NOT NULL,
      "teamId" uuid NOT NULL,
      "userId" uuid NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE "teamMember" ADD CONSTRAINT "PK_teamMember_id" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_teamMember_teamId" ON "teamMember" USING btree ("teamId")`,
    `CREATE INDEX "IDX_teamMember_userId" ON "teamMember" USING btree ("userId")`,
  ],
  user: [
    `CREATE TABLE "user" (
      id uuid NOT NULL,
      name character varying NOT NULL,
      email character varying NOT NULL,
      "emailVerified" boolean DEFAULT false NOT NULL,
      image character varying,
      "firstName" character varying NOT NULL,
      "lastName" character varying NOT NULL,
      role character varying DEFAULT 'user'::character varying NOT NULL,
      "isActive" boolean DEFAULT true NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      banned boolean DEFAULT false NOT NULL,
      "banReason" character varying,
      "banExpires" timestamp with time zone,
      phone character varying,
      "jobTitle" character varying,
      username character varying(39),
      CONSTRAINT "CHK_user_username" CHECK (((username IS NULL) OR ((username)::text ~ '${USERNAME_CHECK}'::text)))
    )`,
    `ALTER TABLE "user" ADD CONSTRAINT "PK_user" PRIMARY KEY (id)`,
    `ALTER TABLE "user" ADD CONSTRAINT "UQ_user_email" UNIQUE (email)`,
    `ALTER TABLE "user" ADD CONSTRAINT "UQ_user_username" UNIQUE (username)`,
    `CREATE INDEX "IDX_user_search_trgm" ON "user" USING gin ("firstName" gin_trgm_ops, "lastName" gin_trgm_ops, email gin_trgm_ops)`,
  ],
  user_role: [
    `CREATE TABLE user_role (
      "userId" uuid NOT NULL,
      "roleId" uuid NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "organizationId" uuid,
      id uuid DEFAULT gen_random_uuid() NOT NULL
    )`,
    `ALTER TABLE user_role ADD CONSTRAINT "PK_user_role" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_user_role_organization" ON user_role USING btree ("organizationId") WHERE ("organizationId" IS NOT NULL)`,
    `CREATE INDEX "IDX_user_role_role" ON user_role USING btree ("roleId")`,
    `CREATE INDEX "IDX_user_role_userId" ON user_role USING btree ("userId")`,
    `CREATE INDEX "IDX_user_role_user_org" ON user_role USING btree ("userId", "organizationId")`,
    `CREATE UNIQUE INDEX "UQ_user_role_global" ON user_role USING btree ("userId", "roleId") WHERE ("organizationId" IS NULL)`,
    `CREATE UNIQUE INDEX "UQ_user_role_scoped" ON user_role USING btree ("userId", "roleId", "organizationId") WHERE ("organizationId" IS NOT NULL)`,
  ],
  user_role_version: [
    `CREATE TABLE user_role_version (
      "userId" uuid NOT NULL,
      version bigint DEFAULT 1 NOT NULL
    )`,
    `ALTER TABLE user_role_version ADD CONSTRAINT "PK_user_role_version" PRIMARY KEY ("userId")`,
  ],
  user_settings: [
    `CREATE TABLE user_settings (
      "userId" uuid NOT NULL,
      theme character varying DEFAULT 'system'::character varying NOT NULL,
      locale character varying DEFAULT 'en'::character varying NOT NULL,
      density character varying DEFAULT 'comfortable'::character varying NOT NULL,
      "weeklyDigest" boolean DEFAULT true NOT NULL,
      "productUpdates" boolean DEFAULT false NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE user_settings ADD CONSTRAINT "PK_user_settings" PRIMARY KEY ("userId")`,
  ],
  verification: [
    `CREATE TABLE verification (
      id uuid NOT NULL,
      identifier character varying NOT NULL,
      value character varying NOT NULL,
      "expiresAt" timestamp with time zone NOT NULL,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL
    )`,
    `ALTER TABLE verification ADD CONSTRAINT "PK_verification" PRIMARY KEY (id)`,
    `CREATE INDEX "IDX_verification_expiresAt" ON verification USING btree ("expiresAt")`,
    `CREATE INDEX "IDX_verification_identifier_createdAt" ON verification USING btree (identifier, "createdAt")`,
  ],
  work_session: [
    `CREATE TABLE work_session (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "organizationId" uuid NOT NULL,
      "projectId" uuid NOT NULL,
      "createdByUserId" uuid NOT NULL,
      "hostId" uuid NOT NULL,
      name character varying NOT NULL,
      "nameSource" character varying,
      slug character varying NOT NULL,
      agent character varying NOT NULL,
      "idempotencyKey" character varying,
      state character varying DEFAULT 'starting'::character varying NOT NULL,
      "stateSeq" integer DEFAULT 0 NOT NULL,
      "agentSessionId" character varying,
      "lastEventAt" timestamp with time zone,
      "stoppedAt" timestamp with time zone,
      "cwdCheckoutId" uuid,
      "lastObservedState" character varying,
      "observedSince" timestamp with time zone,
      "reportHash" character varying,
      "ackedReportHash" character varying,
      "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
      "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
      "launchModel" character varying,
      "launchPermission" character varying DEFAULT 'ask'::character varying,
      "launchEffort" character varying,
      origin character varying(16) DEFAULT 'person'::character varying NOT NULL,
      CONSTRAINT "CHK_work_session_observed_state" CHECK ((("lastObservedState" IS NULL) OR ("lastObservedState" IN ('working', 'blocked', 'idle', 'done', 'unknown')))),
      CONSTRAINT "CHK_work_session_origin" CHECK (origin IN ('person', 'automation')),
      CONSTRAINT "CHK_work_session_state" CHECK (state IN ('starting', 'open', 'failed', 'resolved'))
    )`,
    `ALTER TABLE work_session ADD CONSTRAINT "PK_work_session" PRIMARY KEY (id)`,
    `ALTER TABLE work_session ADD CONSTRAINT "UQ_work_session_organization_id" UNIQUE ("organizationId", id)`,
    `ALTER TABLE work_session ADD CONSTRAINT "UQ_work_session_organization_slug" UNIQUE ("organizationId", slug)`,
    `CREATE INDEX "IDX_work_session_created_by" ON work_session USING btree ("createdByUserId")`,
    `CREATE INDEX "IDX_work_session_host_state" ON work_session USING btree ("hostId", state)`,
    `CREATE INDEX "IDX_work_session_project_state" ON work_session USING btree ("projectId", state)`,
    `CREATE UNIQUE INDEX "UQ_work_session_organization_idempotency" ON work_session USING btree ("organizationId", "idempotencyKey") WHERE ("idempotencyKey" IS NOT NULL)`,
  ],
  work_session_event: [
    `CREATE TABLE work_session_event (
      id uuid DEFAULT gen_random_uuid() NOT NULL,
      "sessionId" uuid NOT NULL,
      seq integer NOT NULL,
      "idempotencyKey" character varying NOT NULL,
      source character varying NOT NULL,
      kind character varying NOT NULL,
      payload jsonb DEFAULT '{}'::jsonb NOT NULL,
      "occurredAt" timestamp with time zone NOT NULL,
      "recordedAt" timestamp with time zone DEFAULT now() NOT NULL,
      CONSTRAINT "CHK_work_session_event_source" CHECK (source IN ('runner', 'api'))
    )`,
    `ALTER TABLE work_session_event ADD CONSTRAINT "PK_work_session_event" PRIMARY KEY (id)`,
    `ALTER TABLE work_session_event ADD CONSTRAINT "UQ_work_session_event_session_key" UNIQUE ("sessionId", "idempotencyKey")`,
    `CREATE INDEX "IDX_work_session_event_first_prompt" ON work_session_event USING btree ("sessionId") WHERE ((kind)::text = 'prompt.first'::text)`,
    `CREATE UNIQUE INDEX "IDX_work_session_event_session_seq" ON work_session_event USING btree ("sessionId", seq)`,
  ],
};

const FOREIGN_KEYS = [
  `ALTER TABLE access_grant ADD CONSTRAINT "FK_access_grant_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE account ADD CONSTRAINT "FK_account_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE api_token ADD CONSTRAINT "FK_api_token_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE automation ADD CONSTRAINT "FK_automation_current_revision" FOREIGN KEY ("currentRevisionId") REFERENCES automation_revision(id) DEFERRABLE INITIALLY DEFERRED`,
  `ALTER TABLE automation ADD CONSTRAINT "FK_automation_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE automation ADD CONSTRAINT "FK_automation_owner" FOREIGN KEY ("ownerUserId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE automation ADD CONSTRAINT "FK_automation_project" FOREIGN KEY ("organizationId", "projectId") REFERENCES project("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE automation_revision ADD CONSTRAINT "FK_automation_revision_automation" FOREIGN KEY ("organizationId", "automationId") REFERENCES automation("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE automation_revision ADD CONSTRAINT "FK_automation_revision_created_by" FOREIGN KEY ("createdByUserId") REFERENCES "user"(id) ON DELETE SET NULL`,
  `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_automation" FOREIGN KEY ("organizationId", "automationId") REFERENCES automation("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_inbound_event" FOREIGN KEY ("inboundEventId") REFERENCES inbound_event(id) ON DELETE SET NULL`,
  `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_requested_by" FOREIGN KEY ("requestedByUserId") REFERENCES "user"(id) ON DELETE SET NULL`,
  `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_revision" FOREIGN KEY ("organizationId", "revisionId") REFERENCES automation_revision("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_session" FOREIGN KEY ("organizationId", "sessionId") REFERENCES work_session("organizationId", id) ON DELETE SET NULL ("sessionId")`,
  `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_trigger" FOREIGN KEY ("triggerId") REFERENCES automation_trigger(id) ON DELETE SET NULL`,
  `ALTER TABLE automation_settings ADD CONSTRAINT "FK_automation_settings_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE automation_trigger ADD CONSTRAINT "FK_automation_trigger_automation" FOREIGN KEY ("organizationId", "automationId") REFERENCES automation("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE automation_trigger_subject ADD CONSTRAINT "FK_automation_trigger_subject_trigger" FOREIGN KEY ("triggerId") REFERENCES automation_trigger(id) ON DELETE CASCADE`,
  `ALTER TABLE github_installation ADD CONSTRAINT "FK_github_installation_installed_by" FOREIGN KEY ("installedByUserId") REFERENCES "user"(id) ON DELETE RESTRICT`,
  `ALTER TABLE github_installation ADD CONSTRAINT "FK_github_installation_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE host_event ADD CONSTRAINT "FK_host_event_host" FOREIGN KEY ("hostId") REFERENCES host(id) ON DELETE CASCADE`,
  `ALTER TABLE host_inventory ADD CONSTRAINT "FK_host_inventory_host" FOREIGN KEY ("hostId") REFERENCES host(id) ON DELETE CASCADE`,
  `ALTER TABLE host_network ADD CONSTRAINT "FK_host_network_host" FOREIGN KEY ("hostId") REFERENCES host(id) ON DELETE CASCADE`,
  `ALTER TABLE host ADD CONSTRAINT "FK_host_owner" FOREIGN KEY ("ownerUserId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE host_pairing_token ADD CONSTRAINT "FK_host_pairing_token_host" FOREIGN KEY ("redeemedHostId") REFERENCES host(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED`,
  `ALTER TABLE host_pairing_token ADD CONSTRAINT "FK_host_pairing_token_owner" FOREIGN KEY ("ownerUserId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE host_presence ADD CONSTRAINT "FK_host_presence_current_network" FOREIGN KEY ("currentNetworkId") REFERENCES host_network(id) ON DELETE SET NULL`,
  `ALTER TABLE host_presence ADD CONSTRAINT "FK_host_presence_host" FOREIGN KEY ("hostId") REFERENCES host(id) ON DELETE CASCADE`,
  `ALTER TABLE inbound_event ADD CONSTRAINT "FK_inbound_event_delivery" FOREIGN KEY ("inboundDeliveryId") REFERENCES inbound_delivery(id) ON DELETE SET NULL`,
  `ALTER TABLE inbound_event ADD CONSTRAINT "FK_inbound_event_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE invitation ADD CONSTRAINT "FK_invitation_inviter" FOREIGN KEY ("inviterId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE invitation ADD CONSTRAINT "FK_invitation_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE invitation ADD CONSTRAINT "FK_invitation_team" FOREIGN KEY ("teamId") REFERENCES team(id) ON DELETE SET NULL`,
  `ALTER TABLE member ADD CONSTRAINT "FK_member_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE member ADD CONSTRAINT "FK_member_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE "oauthAccessToken" ADD CONSTRAINT "FK_oauthAccessToken_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE "oauthConsent" ADD CONSTRAINT "FK_oauthConsent_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE project ADD CONSTRAINT "FK_project_created_by" FOREIGN KEY ("createdByUserId") REFERENCES "user"(id) ON DELETE SET NULL`,
  `ALTER TABLE project ADD CONSTRAINT "FK_project_default_host" FOREIGN KEY ("defaultHostId") REFERENCES host(id) ON DELETE SET NULL`,
  `ALTER TABLE project ADD CONSTRAINT "FK_project_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE RESTRICT`,
  `ALTER TABLE project_repository ADD CONSTRAINT "FK_project_repository_installation" FOREIGN KEY ("organizationId", "installationId") REFERENCES github_installation("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE project_repository ADD CONSTRAINT "FK_project_repository_project" FOREIGN KEY ("organizationId", "projectId") REFERENCES project("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE role ADD CONSTRAINT "FK_role_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE session ADD CONSTRAINT "FK_session_activeOrganization" FOREIGN KEY ("activeOrganizationId") REFERENCES organization(id) ON DELETE SET NULL`,
  `ALTER TABLE session ADD CONSTRAINT "FK_session_activeTeam" FOREIGN KEY ("activeTeamId") REFERENCES team(id) ON DELETE SET NULL`,
  `ALTER TABLE session_checkout ADD CONSTRAINT "FK_session_checkout_installation" FOREIGN KEY ("organizationId", "installationId") REFERENCES github_installation("organizationId", id) ON DELETE RESTRICT`,
  `ALTER TABLE session_checkout ADD CONSTRAINT "FK_session_checkout_session" FOREIGN KEY ("organizationId", "sessionId") REFERENCES work_session("organizationId", id) ON DELETE RESTRICT`,
  `ALTER TABLE session ADD CONSTRAINT "FK_session_impersonatedBy" FOREIGN KEY ("impersonatedBy") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE session_turn ADD CONSTRAINT "FK_session_turn_session" FOREIGN KEY ("organizationId", "sessionId") REFERENCES work_session("organizationId", id) ON DELETE CASCADE`,
  `ALTER TABLE session ADD CONSTRAINT "FK_session_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE "teamMember" ADD CONSTRAINT "FK_teamMember_team" FOREIGN KEY ("teamId") REFERENCES team(id) ON DELETE CASCADE`,
  `ALTER TABLE "teamMember" ADD CONSTRAINT "FK_teamMember_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE team ADD CONSTRAINT "FK_team_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE user_role ADD CONSTRAINT "FK_user_role_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
  `ALTER TABLE user_role ADD CONSTRAINT "FK_user_role_role" FOREIGN KEY ("roleId") REFERENCES role(id) ON DELETE CASCADE`,
  `ALTER TABLE user_role ADD CONSTRAINT "FK_user_role_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE user_role_version ADD CONSTRAINT "FK_user_role_version_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE user_settings ADD CONSTRAINT "FK_user_settings_user" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE`,
  `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_created_by" FOREIGN KEY ("createdByUserId") REFERENCES "user"(id) ON DELETE RESTRICT`,
  `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_cwd_checkout" FOREIGN KEY (id, "cwdCheckoutId") REFERENCES session_checkout("sessionId", id) ON DELETE SET NULL ("cwdCheckoutId") DEFERRABLE INITIALLY DEFERRED`,
  `ALTER TABLE work_session_event ADD CONSTRAINT "FK_work_session_event_session" FOREIGN KEY ("sessionId") REFERENCES work_session(id) ON DELETE RESTRICT`,
  `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_host" FOREIGN KEY ("hostId") REFERENCES host(id) ON DELETE RESTRICT`,
  `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE RESTRICT`,
  `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_project" FOREIGN KEY ("organizationId", "projectId") REFERENCES project("organizationId", id) ON DELETE RESTRICT`,
];

export class InitialSchema1790900000000 implements MigrationInterface {
  name = 'InitialSchema1790900000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const statement of [...EXTENSIONS, ...Object.values(TABLES).flat(), ...FOREIGN_KEYS]) {
      await queryRunner.query(statement);
    }
    await queryRunner.query(
      `INSERT INTO "role" ("id", "name", "description", "isSystem", "organizationId", "permissions") VALUES
       (gen_random_uuid(), 'admin', 'Full access to everything.', true, NULL,
        '[{"action": "manage", "subject": "all"}]'::jsonb),
       (gen_random_uuid(), 'superadmin', 'Platform super administrator (admin plugin: ban, impersonate, manage users).', true, NULL,
        '[{"action": "manage", "subject": "all"}]'::jsonb),
       (gen_random_uuid(), 'user', 'Standard authenticated user.', true, NULL,
        '[{"action": "read", "subject": "ApiToken", "conditions": {"userId": "\${user.id}"}},
          {"action": "create", "subject": "ApiToken", "conditions": {"userId": "\${user.id}"}},
          {"action": "delete", "subject": "ApiToken", "conditions": {"userId": "\${user.id}"}},
          {"action": "read", "subject": "Organization"},
          {"action": "create", "subject": "Organization"},
          {"action": "manage", "subject": "Host", "conditions": {"ownerUserId": "\${user.id}"}}]'::jsonb),
       (gen_random_uuid(), 'owner', 'Administers the organization it is granted in.', true, NULL,
        '[{"action": "manage", "subject": "Organization", "conditions": {"id": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Member", "conditions": {"organizationId": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Invitation", "conditions": {"organizationId": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Workspace", "conditions": {"organizationId": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Role", "conditions": {"organizationId": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Installation", "conditions": {"organizationId": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Project", "conditions": {"organizationId": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Session", "conditions": {"organizationId": "\${activeOrganizationId}"}},
          {"action": "manage", "subject": "Automation", "conditions": {"organizationId": "\${activeOrganizationId}"}}]'::jsonb)
`,
    );
    await queryRunner.query(`INSERT INTO "role_catalog_version" ("id", "version") VALUES (1, 1)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP TABLE ${Object.keys(TABLES)
        .map((table) => `"${table}"`)
        .join(', ')} CASCADE`,
    );
  }
}
