// Code generated by packages/shared/scripts/emit-agent-catalog.cjs from
// packages/shared/src/agents/catalog.ts; DO NOT EDIT.

package domain

// agentUpdates is each agent's `update` entry of the catalog, keyed by the
// executable it runs on: the argv, appended to that executable, that brings
// the CLI to its latest release in place.
var agentUpdates = map[string][]string{
	"claude":   {"update"},
	"codex":    {"update"},
	"opencode": {"upgrade"},
	"grok":     {"update"},
}
