// Code generated by packages/shared/scripts/emit-agent-catalog.cjs from
// packages/shared/src/agents/catalog.ts; DO NOT EDIT.

package domain

// agentUpdates is each agent's `update` entry of the catalog, keyed by the
// executable it runs on: the argv, appended to that executable, that updates
// the CLI in place without asking. An agent whose updater asks has no row.
var agentUpdates = map[string][]string{
	"claude": {"update"},
	"codex":  {"update"},
	"grok":   {"update"},
}
