import type { SchemaSlice } from './schema-slice';

/** `automation`, `automation_revision`, `automation_run`, `automation_settings`, `automation_trigger`, `automation_trigger_subject`. See each table's ORM entity under `src/automations/` for why it is shaped this way. */
export const automations: SchemaSlice = {
  tables: {
    automation: [
      `CREATE TABLE automation (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "organizationId" uuid NOT NULL,
        "projectId" uuid NOT NULL,
        "ownerUserId" uuid NOT NULL,
        name character varying(200) NOT NULL,
        "currentRevisionId" uuid NOT NULL,
        "pausedAt" timestamp with time zone,
        "pausedReason" character varying(32),
        "deletedAt" timestamp with time zone,
        overlap character varying(8),
        "maxRunsPerHour" integer,
        version integer DEFAULT 1 NOT NULL,
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_automation_max_runs" CHECK (("maxRunsPerHour" >= 1)),
        CONSTRAINT "CHK_automation_name" CHECK ((char_length((name)::text) > 0)),
        CONSTRAINT "CHK_automation_overlap" CHECK (overlap IN ('skip', 'queue')),
        CONSTRAINT "CHK_automation_paused" CHECK ((("pausedAt" IS NULL) = ("pausedReason" IS NULL))),
        CONSTRAINT "CHK_automation_paused_reason" CHECK ("pausedReason" IN ('user', 'project_archived', 'host_unpaired', 'owner_lost_access')),
        CONSTRAINT "CHK_automation_version" CHECK ((version >= 1))
      )`,
      `ALTER TABLE automation ADD CONSTRAINT "PK_automation" PRIMARY KEY (id)`,
      `ALTER TABLE automation ADD CONSTRAINT "UQ_automation_organization_id" UNIQUE ("organizationId", id)`,
      `CREATE INDEX "IDX_automation_current_revision" ON automation USING btree ("currentRevisionId")`,
      `CREATE INDEX "IDX_automation_owner" ON automation USING btree ("ownerUserId")`,
      `CREATE INDEX "IDX_automation_project" ON automation USING btree ("organizationId", "projectId")`,
    ],
    automation_revision: [
      `CREATE TABLE automation_revision (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "organizationId" uuid NOT NULL,
        "automationId" uuid NOT NULL,
        number integer NOT NULL,
        "hostId" uuid NOT NULL,
        agent character varying(32) NOT NULL,
        model character varying(128),
        permission character varying(8) DEFAULT 'auto'::character varying NOT NULL,
        effort character varying(16),
        prompt text NOT NULL,
        repositories jsonb NOT NULL,
        "createdByUserId" uuid,
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_automation_revision_number" CHECK ((number >= 1)),
        CONSTRAINT "CHK_automation_revision_permission" CHECK (permission IN ('auto', 'full')),
        CONSTRAINT "CHK_automation_revision_prompt" CHECK ((char_length(prompt) > 0)),
        CONSTRAINT "CHK_automation_revision_repositories" CHECK (((jsonb_typeof(repositories) = 'array'::text) AND (jsonb_array_length(repositories) >= 1)))
      )`,
      `ALTER TABLE automation_revision ADD CONSTRAINT "PK_automation_revision" PRIMARY KEY (id)`,
      `ALTER TABLE automation_revision ADD CONSTRAINT "UQ_automation_revision_automation_number" UNIQUE ("automationId", number)`,
      `ALTER TABLE automation_revision ADD CONSTRAINT "UQ_automation_revision_organization_id" UNIQUE ("organizationId", id)`,
      `CREATE INDEX "IDX_automation_revision_automation" ON automation_revision USING btree ("organizationId", "automationId")`,
      `CREATE INDEX "IDX_automation_revision_created_by" ON automation_revision USING btree ("createdByUserId") WHERE ("createdByUserId" IS NOT NULL)`,
      `CREATE INDEX "IDX_automation_revision_host" ON automation_revision USING btree ("hostId")`,
    ],
    automation_run: [
      `CREATE TABLE automation_run (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "organizationId" uuid NOT NULL,
        "automationId" uuid NOT NULL,
        "revisionId" uuid NOT NULL,
        "triggerId" uuid,
        cause character varying(16) NOT NULL,
        "causeKey" character varying(200) NOT NULL,
        "causeSummary" jsonb DEFAULT '{}'::jsonb NOT NULL,
        "inboundEventId" uuid,
        "scheduledFor" timestamp with time zone,
        outcome character varying(16) DEFAULT 'pending'::character varying NOT NULL,
        "skipReason" character varying(40),
        "availableAt" timestamp with time zone DEFAULT now() NOT NULL,
        attempts integer DEFAULT 0 NOT NULL,
        "sessionId" uuid,
        "requestedByUserId" uuid,
        "dispatchedAt" timestamp with time zone,
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_automation_run_attempts" CHECK ((attempts >= 0)),
        CONSTRAINT "CHK_automation_run_cause" CHECK (cause IN ('schedule', 'event', 'manual')),
        CONSTRAINT "CHK_automation_run_cause_summary" CHECK ((jsonb_typeof("causeSummary") = 'object'::text)),
        CONSTRAINT "CHK_automation_run_dispatched" CHECK ((((outcome)::text = 'dispatched'::text) = ("dispatchedAt" IS NOT NULL))),
        CONSTRAINT "CHK_automation_run_outcome" CHECK (outcome IN ('pending', 'skipped', 'expired', 'dispatched')),
        CONSTRAINT "CHK_automation_run_skip_reason" CHECK ((((outcome)::text = 'skipped'::text) = ("skipReason" IS NOT NULL)))
      )`,
      `ALTER TABLE automation_run ADD CONSTRAINT "PK_automation_run" PRIMARY KEY (id)`,
      `ALTER TABLE automation_run ADD CONSTRAINT "UQ_automation_run_automation_cause" UNIQUE ("automationId", "causeKey")`,
      `CREATE INDEX "IDX_automation_run_automation_created" ON automation_run USING btree ("organizationId", "automationId", "createdAt", id)`,
      `CREATE INDEX "IDX_automation_run_created_brin" ON automation_run USING brin ("createdAt")`,
      `CREATE INDEX "IDX_automation_run_dispatched" ON automation_run USING btree ("dispatchedAt") WHERE ((outcome)::text = 'dispatched'::text)`,
      `CREATE INDEX "IDX_automation_run_inbound_event" ON automation_run USING btree ("inboundEventId") WHERE ("inboundEventId" IS NOT NULL)`,
      `CREATE INDEX "IDX_automation_run_organization_created" ON automation_run USING btree ("organizationId", "createdAt", id)`,
      `CREATE INDEX "IDX_automation_run_organization_session" ON automation_run USING btree ("organizationId", "sessionId") WHERE ("sessionId" IS NOT NULL)`,
      `CREATE INDEX "IDX_automation_run_pending" ON automation_run USING btree ("availableAt") WHERE ((outcome)::text = 'pending'::text)`,
      `CREATE INDEX "IDX_automation_run_requested_by" ON automation_run USING btree ("requestedByUserId") WHERE ("requestedByUserId" IS NOT NULL)`,
      `CREATE INDEX "IDX_automation_run_revision" ON automation_run USING btree ("organizationId", "revisionId")`,
      `CREATE INDEX "IDX_automation_run_trigger" ON automation_run USING btree ("triggerId") WHERE ("triggerId" IS NOT NULL)`,
      `CREATE UNIQUE INDEX "UQ_automation_run_session" ON automation_run USING btree ("sessionId") WHERE ("sessionId" IS NOT NULL)`,
    ],
    automation_settings: [
      `CREATE TABLE automation_settings (
        "organizationId" uuid NOT NULL,
        "maxRunsPerAutomationHour" integer,
        "maxRunsPerWorkspaceHour" integer,
        "liveRunsPerHost" integer,
        overlap character varying(8),
        "staleTtlSeconds" integer,
        "missedGraceSeconds" integer,
        "maxRunSeconds" integer,
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_automation_settings_overlap" CHECK (overlap IN ('skip', 'queue')),
        CONSTRAINT "CHK_automation_settings_positive" CHECK (((COALESCE("maxRunsPerAutomationHour", 1) >= 1) AND (COALESCE("maxRunsPerWorkspaceHour", 1) >= 1) AND (COALESCE("liveRunsPerHost", 1) >= 1) AND (COALESCE("staleTtlSeconds", 60) >= 60) AND (COALESCE("missedGraceSeconds", 0) >= 0) AND (COALESCE("maxRunSeconds", 60) >= 60)))
      )`,
      `ALTER TABLE automation_settings ADD CONSTRAINT "PK_automation_settings" PRIMARY KEY ("organizationId")`,
    ],
    automation_trigger: [
      `CREATE TABLE automation_trigger (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "organizationId" uuid NOT NULL,
        "automationId" uuid NOT NULL,
        "position" smallint DEFAULT 0 NOT NULL,
        source character varying(32) NOT NULL,
        "eventType" character varying(64) NOT NULL,
        config jsonb NOT NULL,
        timezone character varying(64),
        "nextFireAt" timestamp with time zone,
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_automation_trigger_config" CHECK ((jsonb_typeof(config) = 'object'::text)),
        CONSTRAINT "CHK_automation_trigger_next_fire" CHECK ((((source)::text = 'schedule'::text) OR ("nextFireAt" IS NULL))),
        CONSTRAINT "CHK_automation_trigger_position" CHECK (("position" >= 0)),
        CONSTRAINT "CHK_automation_trigger_schedule" CHECK ((((source)::text = 'schedule'::text) = (timezone IS NOT NULL))),
        CONSTRAINT "CHK_automation_trigger_source" CHECK (source IN ('schedule', 'github'))
      )`,
      `ALTER TABLE automation_trigger ADD CONSTRAINT "PK_automation_trigger" PRIMARY KEY (id)`,
      `CREATE INDEX "IDX_automation_trigger_automation" ON automation_trigger USING btree ("automationId", "organizationId", "position")`,
      `CREATE INDEX "IDX_automation_trigger_due" ON automation_trigger USING btree ("nextFireAt") WHERE ("nextFireAt" IS NOT NULL)`,
      `CREATE INDEX "IDX_automation_trigger_match" ON automation_trigger USING btree ("organizationId", source, "eventType")`,
    ],
    automation_trigger_subject: [
      `CREATE TABLE automation_trigger_subject (
        "triggerId" uuid NOT NULL,
        "organizationId" uuid NOT NULL,
        "subjectKind" character varying(32) NOT NULL,
        "subjectRef" character varying(128) NOT NULL,
        CONSTRAINT "CHK_automation_trigger_subject_kind" CHECK ((("subjectKind")::text = 'repository'::text))
      )`,
      `ALTER TABLE automation_trigger_subject ADD CONSTRAINT "PK_automation_trigger_subject" PRIMARY KEY ("triggerId", "subjectKind", "subjectRef")`,
      `CREATE INDEX "IDX_automation_trigger_subject_lookup" ON automation_trigger_subject USING btree ("organizationId", "subjectKind", "subjectRef")`,
    ],
  },
  foreignKeys: [
    `ALTER TABLE automation ADD CONSTRAINT "FK_automation_current_revision" FOREIGN KEY ("currentRevisionId") REFERENCES automation_revision(id) DEFERRABLE INITIALLY DEFERRED`,
    `ALTER TABLE automation ADD CONSTRAINT "FK_automation_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
    `ALTER TABLE automation ADD CONSTRAINT "FK_automation_owner" FOREIGN KEY ("ownerUserId") REFERENCES "user"(id) ON DELETE CASCADE`,
    `ALTER TABLE automation ADD CONSTRAINT "FK_automation_project" FOREIGN KEY ("organizationId", "projectId") REFERENCES project("organizationId", id) ON DELETE CASCADE`,
    `ALTER TABLE automation_revision ADD CONSTRAINT "FK_automation_revision_automation" FOREIGN KEY ("organizationId", "automationId") REFERENCES automation("organizationId", id) ON DELETE CASCADE`,
    `ALTER TABLE automation_revision ADD CONSTRAINT "FK_automation_revision_created_by" FOREIGN KEY ("createdByUserId") REFERENCES "user"(id) ON DELETE SET NULL`,
    `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_automation" FOREIGN KEY ("organizationId", "automationId") REFERENCES automation("organizationId", id) ON DELETE CASCADE`,
    `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_inbound_event" FOREIGN KEY ("inboundEventId") REFERENCES inbound_event(id) ON DELETE SET NULL`,
    `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_requested_by" FOREIGN KEY ("requestedByUserId") REFERENCES "user"(id) ON DELETE SET NULL`,
    `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_revision" FOREIGN KEY ("organizationId", "revisionId") REFERENCES automation_revision("organizationId", id) ON DELETE CASCADE`,
    `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_session" FOREIGN KEY ("organizationId", "sessionId") REFERENCES work_session("organizationId", id) ON DELETE SET NULL ("sessionId")`,
    `ALTER TABLE automation_run ADD CONSTRAINT "FK_automation_run_trigger" FOREIGN KEY ("triggerId") REFERENCES automation_trigger(id) ON DELETE SET NULL`,
    `ALTER TABLE automation_settings ADD CONSTRAINT "FK_automation_settings_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE`,
    `ALTER TABLE automation_trigger ADD CONSTRAINT "FK_automation_trigger_automation" FOREIGN KEY ("organizationId", "automationId") REFERENCES automation("organizationId", id) ON DELETE CASCADE`,
    `ALTER TABLE automation_trigger_subject ADD CONSTRAINT "FK_automation_trigger_subject_trigger" FOREIGN KEY ("triggerId") REFERENCES automation_trigger(id) ON DELETE CASCADE`,
  ],
};
