import type { SchemaSlice } from './schema-slice';

/** `session_checkout`, `session_turn`, `work_session`, `work_session_event`. See each table's ORM entity under `src/sessions/` for why it is shaped this way. */
export const sessions: SchemaSlice = {
  tables: {
    session_checkout: [
      `CREATE TABLE session_checkout (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "organizationId" uuid NOT NULL,
        "sessionId" uuid NOT NULL,
        "installationId" uuid NOT NULL,
        "githubRepoId" bigint NOT NULL,
        "repositoryFullName" character varying NOT NULL,
        "storeDirectoryName" character varying,
        "directoryName" character varying NOT NULL,
        mode character varying DEFAULT 'worktree'::character varying NOT NULL,
        "baseBranch" character varying NOT NULL,
        branch character varying NOT NULL,
        "worktreeCreatedAt" timestamp with time zone,
        "pushedAt" timestamp with time zone,
        "removedAt" timestamp with time zone,
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_session_checkout_mode" CHECK (mode IN ('worktree', 'clone'))
      )`,
      `ALTER TABLE session_checkout ADD CONSTRAINT "PK_session_checkout" PRIMARY KEY (id)`,
      `ALTER TABLE session_checkout ADD CONSTRAINT "UQ_session_checkout_session_directory" UNIQUE ("sessionId", "directoryName")`,
      `ALTER TABLE session_checkout ADD CONSTRAINT "UQ_session_checkout_session_id" UNIQUE ("sessionId", id)`,
      `CREATE INDEX "IDX_session_checkout_installation" ON session_checkout USING btree ("organizationId", "installationId")`,
      `CREATE UNIQUE INDEX "UQ_session_checkout_session_repo" ON session_checkout USING btree ("sessionId", "githubRepoId") WHERE ("removedAt" IS NULL)`,
    ],
    session_turn: [
      `CREATE TABLE session_turn (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "organizationId" uuid NOT NULL,
        "sessionId" uuid NOT NULL,
        seq integer NOT NULL,
        origin character varying(16) NOT NULL,
        drive character varying(16) DEFAULT 'interactive'::character varying NOT NULL,
        state character varying(20) DEFAULT 'queued'::character varying NOT NULL,
        prompt text,
        "observedWorking" boolean DEFAULT false NOT NULL,
        "startedAt" timestamp with time zone,
        "endedAt" timestamp with time zone,
        "exitCode" integer,
        "agentSessionId" character varying(128),
        result text,
        "failureDetail" text,
        "costUsd" numeric(12,6),
        "permissionDenials" integer DEFAULT 0 NOT NULL,
        "outputRef" character varying(512),
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_session_turn_cost" CHECK ((("costUsd" IS NULL) OR ("costUsd" >= (0)::numeric))),
        CONSTRAINT "CHK_session_turn_denials" CHECK (("permissionDenials" >= 0)),
        CONSTRAINT "CHK_session_turn_drive" CHECK (drive IN ('interactive', 'headless')),
        CONSTRAINT "CHK_session_turn_ended" CHECK ((("endedAt" IS NULL) OR ("startedAt" IS NULL) OR ("endedAt" >= "startedAt"))),
        CONSTRAINT "CHK_session_turn_origin" CHECK (origin IN ('person', 'automation', 'follow_up')),
        CONSTRAINT "CHK_session_turn_seq" CHECK ((seq >= 1)),
        CONSTRAINT "CHK_session_turn_state" CHECK (state IN ('queued', 'in_progress', 'requires_action', 'completed', 'failed', 'cancelled', 'expired'))
      )`,
      `ALTER TABLE session_turn ADD CONSTRAINT "PK_session_turn" PRIMARY KEY (id)`,
      `ALTER TABLE session_turn ADD CONSTRAINT "UQ_session_turn_session_seq" UNIQUE ("sessionId", seq)`,
      `CREATE INDEX "IDX_session_turn_live" ON session_turn USING btree ("sessionId") WHERE (state IN ('queued', 'in_progress', 'requires_action'))`,
      `CREATE INDEX "IDX_session_turn_organization_session" ON session_turn USING btree ("organizationId", "sessionId")`,
    ],
    work_session: [
      `CREATE TABLE work_session (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "organizationId" uuid NOT NULL,
        "projectId" uuid NOT NULL,
        "createdByUserId" uuid NOT NULL,
        "hostId" uuid NOT NULL,
        name character varying NOT NULL,
        "nameSource" character varying,
        slug character varying NOT NULL,
        agent character varying NOT NULL,
        "idempotencyKey" character varying,
        state character varying DEFAULT 'starting'::character varying NOT NULL,
        "stateSeq" integer DEFAULT 0 NOT NULL,
        "agentSessionId" character varying,
        "lastEventAt" timestamp with time zone,
        "stoppedAt" timestamp with time zone,
        "cwdCheckoutId" uuid,
        "lastObservedState" character varying,
        "observedSince" timestamp with time zone,
        "reportHash" character varying,
        "ackedReportHash" character varying,
        "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
        "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
        "launchModel" character varying,
        "launchPermission" character varying DEFAULT 'ask'::character varying,
        "launchEffort" character varying,
        origin character varying(16) DEFAULT 'person'::character varying NOT NULL,
        CONSTRAINT "CHK_work_session_observed_state" CHECK ((("lastObservedState" IS NULL) OR ("lastObservedState" IN ('working', 'blocked', 'idle', 'done', 'unknown')))),
        CONSTRAINT "CHK_work_session_origin" CHECK (origin IN ('person', 'automation')),
        CONSTRAINT "CHK_work_session_state" CHECK (state IN ('starting', 'open', 'failed', 'resolved'))
      )`,
      `ALTER TABLE work_session ADD CONSTRAINT "PK_work_session" PRIMARY KEY (id)`,
      `ALTER TABLE work_session ADD CONSTRAINT "UQ_work_session_organization_id" UNIQUE ("organizationId", id)`,
      `ALTER TABLE work_session ADD CONSTRAINT "UQ_work_session_organization_slug" UNIQUE ("organizationId", slug)`,
      `CREATE INDEX "IDX_work_session_created_by" ON work_session USING btree ("createdByUserId")`,
      `CREATE INDEX "IDX_work_session_host_state" ON work_session USING btree ("hostId", state)`,
      `CREATE INDEX "IDX_work_session_project_state" ON work_session USING btree ("projectId", state)`,
      `CREATE UNIQUE INDEX "UQ_work_session_organization_idempotency" ON work_session USING btree ("organizationId", "idempotencyKey") WHERE ("idempotencyKey" IS NOT NULL)`,
    ],
    work_session_event: [
      `CREATE TABLE work_session_event (
        id uuid DEFAULT gen_random_uuid() NOT NULL,
        "sessionId" uuid NOT NULL,
        seq integer NOT NULL,
        "idempotencyKey" character varying NOT NULL,
        source character varying NOT NULL,
        kind character varying NOT NULL,
        payload jsonb DEFAULT '{}'::jsonb NOT NULL,
        "occurredAt" timestamp with time zone NOT NULL,
        "recordedAt" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "CHK_work_session_event_source" CHECK (source IN ('runner', 'api'))
      )`,
      `ALTER TABLE work_session_event ADD CONSTRAINT "PK_work_session_event" PRIMARY KEY (id)`,
      `ALTER TABLE work_session_event ADD CONSTRAINT "UQ_work_session_event_session_key" UNIQUE ("sessionId", "idempotencyKey")`,
      `CREATE INDEX "IDX_work_session_event_first_prompt" ON work_session_event USING btree ("sessionId") WHERE ((kind)::text = 'prompt.first'::text)`,
      `CREATE UNIQUE INDEX "IDX_work_session_event_session_seq" ON work_session_event USING btree ("sessionId", seq)`,
    ],
  },
  foreignKeys: [
    `ALTER TABLE session_checkout ADD CONSTRAINT "FK_session_checkout_installation" FOREIGN KEY ("organizationId", "installationId") REFERENCES github_installation("organizationId", id) ON DELETE RESTRICT`,
    `ALTER TABLE session_checkout ADD CONSTRAINT "FK_session_checkout_session" FOREIGN KEY ("organizationId", "sessionId") REFERENCES work_session("organizationId", id) ON DELETE RESTRICT`,
    `ALTER TABLE session_turn ADD CONSTRAINT "FK_session_turn_session" FOREIGN KEY ("organizationId", "sessionId") REFERENCES work_session("organizationId", id) ON DELETE CASCADE`,
    `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_created_by" FOREIGN KEY ("createdByUserId") REFERENCES "user"(id) ON DELETE RESTRICT`,
    `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_cwd_checkout" FOREIGN KEY (id, "cwdCheckoutId") REFERENCES session_checkout("sessionId", id) ON DELETE SET NULL ("cwdCheckoutId") DEFERRABLE INITIALLY DEFERRED`,
    `ALTER TABLE work_session_event ADD CONSTRAINT "FK_work_session_event_session" FOREIGN KEY ("sessionId") REFERENCES work_session(id) ON DELETE RESTRICT`,
    `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_host" FOREIGN KEY ("hostId") REFERENCES host(id) ON DELETE RESTRICT`,
    `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_organization" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE RESTRICT`,
    `ALTER TABLE work_session ADD CONSTRAINT "FK_work_session_project" FOREIGN KEY ("organizationId", "projectId") REFERENCES project("organizationId", id) ON DELETE RESTRICT`,
  ],
};
