// Code generated by packages/shared/scripts/emit-link-protocol.cjs from
// packages/shared/protocol-schema/protocol.schema.json; DO NOT EDIT.

package link

import (
	"time"

	hostdomain "github.com/jordiparracrespo/oppenheimer/apps/runner/internal/host/domain"
)

// ProtocolVersion is the one version of the wire this runner speaks: it
// advertises it as `hello.protocol.max`.
const ProtocolVersion = 1

// The close codes the control plane uses on the link, `4000 + HTTP status`.
// CloseUnpaired is terminal: its handshake twin is a 410 carrying
// RefusalHeader: RefusalUnpaired — see ErrUnpaired.
const (
	CloseHelloExpected    = 4400
	CloseHelloTimeout     = 4408
	CloseReplaced         = 4409
	CloseUnpaired         = 4410
	CloseProtocolMismatch = 4426
)

// RefusalHeader and its values mark the control plane's own refusal at the
// handshake. A bare 410 is not trusted — any proxy in front of the control
// plane can answer one — and a host that took a stranger's as "unpaired"
// would stop dialling for good.
const (
	RefusalHeader   = "X-Oppenheimer-Refusal"
	RefusalUnpaired = "host-unpaired"
)

// FrameHeader is the 4-byte big-endian attachment id every binary frame on
// the link starts with (01-protocol, "Framing").
const FrameHeader = 4

// CreditWindow is 01's 256 KB: the bytes an attachment may have in flight
// before its PTY reads pause. A runaway build stalls its own pane, never the
// link.
const CreditWindow = 262144

// MaxFrameBytes is the largest frame either peer puts on the link: the
// control plane closes a link that sends a bigger one with 1009, so the
// runner reads no bigger one and never sends one.
const MaxFrameBytes = 524288

// MaxEventPayloadBytes caps an event's JSON payload string, because an event
// never carries pane text.
const MaxEventPayloadBytes = 8192

// The hello capabilities: commands a runner takes beyond its protocol
// version's baseline.
const (
	CapabilitySessionImage        = "session.image"
	CapabilitySessionCreateImages = "session.create.images"
	CapabilityRepositoryPrepare   = "repository.prepare"
)

// The `type` of every message on the link.
const (
	TypeHello              = "hello"
	TypeHeartbeat          = "heartbeat"
	TypeHint               = "hint"
	TypeWelcome            = "welcome"
	TypeCommandFailed      = "command.failed"
	TypeSessionDetach      = "session.detach"
	TypeAttachmentClosed   = "attachment.closed"
	TypeEventsAppend       = "events.append"
	TypeEventsAck          = "events.ack"
	TypeSessionCreate      = "session.create"
	TypeSessionAttach      = "session.attach"
	TypeSessionInput       = "session.input"
	TypeSessionImage       = "session.image"
	TypeAttachmentCredit   = "attachment.credit"
	TypeSessionResize      = "session.resize"
	TypeSessionWindowOpen  = "session.window.open"
	TypeSessionWindowClose = "session.window.close"
	TypeSessionClose       = "session.close"
	TypeSessionStop        = "session.stop"
	TypeSessionRestart     = "session.restart"
	TypeHostPreflight      = "host.preflight"
	TypeHostUpdate         = "host.update"
	TypeCredentialsToken   = "credentials.token"
	TypeCredentialsGrant   = "credentials.grant"
	TypeCredentialsRevoke  = "credentials.revoke"
	TypeRepositoryPrepare  = "repository.prepare"
)

// MessageTypes is every message type on the link, in the schema's order.
var MessageTypes = []string{
	TypeHello,
	TypeHeartbeat,
	TypeHint,
	TypeWelcome,
	TypeCommandFailed,
	TypeSessionDetach,
	TypeAttachmentClosed,
	TypeEventsAppend,
	TypeEventsAck,
	TypeSessionCreate,
	TypeSessionAttach,
	TypeSessionInput,
	TypeSessionImage,
	TypeAttachmentCredit,
	TypeSessionResize,
	TypeSessionWindowOpen,
	TypeSessionWindowClose,
	TypeSessionClose,
	TypeSessionStop,
	TypeSessionRestart,
	TypeHostPreflight,
	TypeHostUpdate,
	TypeCredentialsToken,
	TypeCredentialsGrant,
	TypeCredentialsRevoke,
	TypeRepositoryPrepare,
}

// NewMessage returns a pointer to a new struct for a message type, and false
// for a type this runner does not know.
func NewMessage(messageType string) (any, bool) {
	switch messageType {
	case TypeHello:
		return new(Hello), true
	case TypeHeartbeat:
		return new(Heartbeat), true
	case TypeHint:
		return new(Hint), true
	case TypeWelcome:
		return new(Welcome), true
	case TypeCommandFailed:
		return new(CommandFailed), true
	case TypeSessionDetach:
		return new(SessionDetach), true
	case TypeAttachmentClosed:
		return new(AttachmentClosed), true
	case TypeEventsAppend:
		return new(EventsAppend), true
	case TypeEventsAck:
		return new(EventsAck), true
	case TypeSessionCreate:
		return new(SessionCreate), true
	case TypeSessionAttach:
		return new(SessionAttach), true
	case TypeSessionInput:
		return new(SessionInput), true
	case TypeSessionImage:
		return new(SessionImage), true
	case TypeAttachmentCredit:
		return new(AttachmentCredit), true
	case TypeSessionResize:
		return new(SessionResize), true
	case TypeSessionWindowOpen:
		return new(SessionWindowOpen), true
	case TypeSessionWindowClose:
		return new(SessionWindowClose), true
	case TypeSessionClose:
		return new(SessionClose), true
	case TypeSessionStop:
		return new(SessionStop), true
	case TypeSessionRestart:
		return new(SessionRestart), true
	case TypeHostPreflight:
		return new(HostPreflight), true
	case TypeHostUpdate:
		return new(HostUpdate), true
	case TypeCredentialsToken:
		return new(CredentialsToken), true
	case TypeCredentialsGrant:
		return new(CredentialsGrant), true
	case TypeCredentialsRevoke:
		return new(CredentialsRevoke), true
	case TypeRepositoryPrepare:
		return new(RepositoryPrepare), true
	}
	return nil, false
}

// Hello is the `hello` message.
type Hello struct {
	Type          string            `json:"type"`
	RunnerVersion string            `json:"runnerVersion"`
	Protocol      Range             `json:"protocol"`
	RunID         string            `json:"runId"`
	Host          hostdomain.Facts  `json:"host"`
	Sessions      []SessionSnapshot `json:"sessions"`
	Capabilities  []string          `json:"capabilities"`
}

// Range is Hello.Protocol.
type Range struct {
	Min int `json:"min"`
	Max int `json:"max"`
}

// Heartbeat is the `heartbeat` message.
type Heartbeat struct {
	Type     string            `json:"type"`
	SentAt   time.Time         `json:"sentAt"`
	Channel  string            `json:"channel"`
	Host     hostdomain.Facts  `json:"host"`
	Load     Load              `json:"load"`
	Sessions []SessionSnapshot `json:"sessions"`
}

// Load is Heartbeat.Load.
type Load struct {
	LoadAverage1m        float64 `json:"loadAverage1m"`
	MemoryAvailableBytes uint64  `json:"memoryAvailableBytes,omitempty"`
}

// Hint is the `hint` message.
type Hint struct {
	Type              string `json:"type"`
	Kind              string `json:"kind"`
	RetryAfterSeconds int    `json:"retryAfterSeconds,omitempty"`
	Detail            string `json:"detail,omitempty"`
}

// Welcome is the `welcome` message.
type Welcome struct {
	Type           string `json:"type"`
	Protocol       int    `json:"protocol"`
	KeyFingerprint string `json:"keyFingerprint"`
	HostID         string `json:"hostId"`
	Epoch          uint64 `json:"epoch"`
}

// CommandFailed is the `command.failed` message.
type CommandFailed struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	Code      string `json:"code"`
	Detail    string `json:"detail,omitempty"`
}

// SessionDetach is the `session.detach` message.
type SessionDetach struct {
	Type         string `json:"type"`
	CommandID    string `json:"commandId"`
	SessionID    string `json:"sessionId"`
	AttachmentID uint32 `json:"attachmentId"`
}

// AttachmentClosed is the `attachment.closed` message.
type AttachmentClosed struct {
	Type         string `json:"type"`
	AttachmentID uint32 `json:"attachmentId"`
	Reason       string `json:"reason,omitempty"`
}

// EventsAppend is the `events.append` message.
type EventsAppend struct {
	Type      string  `json:"type"`
	BatchID   string  `json:"batchId"`
	SessionID string  `json:"sessionId"`
	Events    []Event `json:"events"`
}

// Event is EventsAppend.Events.
type Event struct {
	IdempotencyKey string    `json:"idempotencyKey"`
	Kind           string    `json:"kind"`
	Payload        string    `json:"payload"`
	OccurredAt     time.Time `json:"occurredAt"`
}

// EventsAck is the `events.ack` message.
type EventsAck struct {
	Type     string              `json:"type"`
	BatchID  string              `json:"batchId"`
	Accepted []string            `json:"accepted"`
	Rejected []EventsAckRejected `json:"rejected,omitempty"`
}

// EventsAckRejected is EventsAck.Rejected.
type EventsAckRejected struct {
	IdempotencyKey string `json:"idempotencyKey"`
	Reason         string `json:"reason"`
}

// SessionCreate is the `session.create` message.
type SessionCreate struct {
	Type             string                `json:"type"`
	CommandID        string                `json:"commandId"`
	SessionID        string                `json:"sessionId"`
	OrganizationSlug string                `json:"organizationSlug"`
	SessionSlug      string                `json:"sessionSlug"`
	Agent            string                `json:"agent"`
	Launch           LaunchOptions         `json:"launch"`
	Prompt           string                `json:"prompt,omitempty"`
	Images           []SessionCreateImages `json:"images,omitempty"`
	Branch           string                `json:"branch"`
	Checkouts        []Checkout            `json:"checkouts"`
	CwdCheckoutID    *string               `json:"cwdCheckoutId"`
}

// LaunchOptions is SessionCreate.Launch.
type LaunchOptions struct {
	Model        string `json:"model,omitempty"`
	Permission   string `json:"permission,omitempty"`
	Effort       string `json:"effort,omitempty"`
	Conversation string `json:"conversation,omitempty"`
	Resume       bool   `json:"resume,omitempty"`
}

// SessionCreateImages is SessionCreate.Images.
type SessionCreateImages struct {
	ImageID   string `json:"imageId"`
	MediaType string `json:"mediaType"`
}

// Checkout is SessionCreate.Checkouts.
type Checkout struct {
	CheckoutID         string `json:"checkoutId"`
	GithubRepoID       int64  `json:"githubRepoId"`
	RepositoryFullName string `json:"repositoryFullName"`
	DirectoryName      string `json:"directoryName"`
	BaseBranch         string `json:"baseBranch"`
}

// SessionAttach is the `session.attach` message.
type SessionAttach struct {
	Type         string `json:"type"`
	CommandID    string `json:"commandId"`
	SessionID    string `json:"sessionId"`
	Window       int    `json:"window"`
	AttachmentID uint32 `json:"attachmentId"`
	Cols         int    `json:"cols"`
	Rows         int    `json:"rows"`
}

// SessionInput is the `session.input` message.
type SessionInput struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	SessionID string `json:"sessionId"`
	Window    int    `json:"window"`
	Data      string `json:"data"`
}

// SessionImage is the `session.image` message.
type SessionImage struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	SessionID string `json:"sessionId"`
	Window    int    `json:"window"`
	MediaType string `json:"mediaType"`
}

// AttachmentCredit is the `attachment.credit` message.
type AttachmentCredit struct {
	Type         string `json:"type"`
	AttachmentID uint32 `json:"attachmentId"`
	Bytes        int    `json:"bytes"`
}

// SessionResize is the `session.resize` message.
type SessionResize struct {
	Type         string `json:"type"`
	CommandID    string `json:"commandId"`
	SessionID    string `json:"sessionId"`
	AttachmentID uint32 `json:"attachmentId"`
	Cols         int    `json:"cols"`
	Rows         int    `json:"rows"`
}

// SessionWindowOpen is the `session.window.open` message.
type SessionWindowOpen struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	SessionID string `json:"sessionId"`
	Name      string `json:"name,omitempty"`
}

// SessionWindowClose is the `session.window.close` message.
type SessionWindowClose struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	SessionID string `json:"sessionId"`
	Window    int    `json:"window"`
}

// SessionClose is the `session.close` message.
type SessionClose struct {
	Type               string `json:"type"`
	CommandID          string `json:"commandId"`
	SessionID          string `json:"sessionId"`
	AcceptUnpushedWork bool   `json:"acceptUnpushedWork"`
}

// SessionStop is the `session.stop` message.
type SessionStop struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	SessionID string `json:"sessionId"`
}

// SessionRestart is the `session.restart` message.
type SessionRestart struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	SessionID string `json:"sessionId"`
}

// HostPreflight is the `host.preflight` message.
type HostPreflight struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
}

// HostUpdate is the `host.update` message.
type HostUpdate struct {
	Type      string `json:"type"`
	CommandID string `json:"commandId"`
	Version   string `json:"version"`
	Channel   string `json:"channel"`
}

// CredentialsToken is the `credentials.token` message.
type CredentialsToken struct {
	Type         string `json:"type"`
	RequestID    string `json:"requestId"`
	SessionID    string `json:"sessionId"`
	CheckoutID   string `json:"checkoutId"`
	GithubRepoID int64  `json:"githubRepoId"`
}

// CredentialsGrant is the `credentials.grant` message.
type CredentialsGrant struct {
	Type       string    `json:"type"`
	RequestID  string    `json:"requestId"`
	SessionID  string    `json:"sessionId"`
	CheckoutID string    `json:"checkoutId"`
	Sealed     string    `json:"sealed"`
	ExpiresAt  time.Time `json:"expiresAt"`
}

// CredentialsRevoke is the `credentials.revoke` message.
type CredentialsRevoke struct {
	Type       string `json:"type"`
	RequestID  string `json:"requestId"`
	SessionID  string `json:"sessionId"`
	CheckoutID string `json:"checkoutId"`
}

// RepositoryPrepare is the `repository.prepare` message.
type RepositoryPrepare struct {
	Type               string    `json:"type"`
	CommandID          string    `json:"commandId"`
	GithubRepoID       int64     `json:"githubRepoId"`
	RepositoryFullName string    `json:"repositoryFullName"`
	BaseBranch         string    `json:"baseBranch"`
	Sealed             string    `json:"sealed"`
	ExpiresAt          time.Time `json:"expiresAt"`
}

// SessionSnapshot is `#/$defs/sessionSnapshot`.
type SessionSnapshot struct {
	SessionID      string   `json:"sessionId"`
	Agent          string   `json:"agent"`
	Observed       string   `json:"observed"`
	StateSeconds   int      `json:"stateSeconds"`
	Windows        []Window `json:"windows"`
	AgentSessionID *string  `json:"agentSessionId"`
	ReportHash     *string  `json:"reportHash"`
	LoginURL       *string  `json:"loginUrl"`
}

// Window is SessionSnapshot.Windows.
type Window struct {
	Index int    `json:"index"`
	Name  string `json:"name,omitempty"`
}
