// Code generated by packages/shared/scripts/emit-session-step.cjs from
// packages/shared/src/protocol/session-step.ts; DO NOT EDIT.

package link

// SessionStepKind is the event kind a start step is logged as.
const SessionStepKind = "session.step"

// SessionStep is one step of starting a session, in the order the host runs them.
type SessionStep string

const (
	SessionStepHost     SessionStep = "host"
	SessionStepClone    SessionStep = "clone"
	SessionStepWorktree SessionStep = "worktree"
	SessionStepAgent    SessionStep = "agent"
)

// SessionStepStatus is where a step is. A failure is `session.failed`, not a status.
type SessionStepStatus string

const (
	SessionStepRunning SessionStepStatus = "running"
	SessionStepDone    SessionStepStatus = "done"
)

// SessionStepPayload is the payload of a SessionStepKind event.
type SessionStepPayload struct {
	Step       SessionStep       `json:"step"`
	Status     SessionStepStatus `json:"status"`
	DurationMs *int64            `json:"durationMs,omitempty"`
}
