export const CALENDAR_EVENT_REPOSITORY = Symbol('CALENDAR_EVENT_REPOSITORY');
export const CALENDAR_CONNECTION_REPOSITORY = Symbol('CALENDAR_CONNECTION_REPOSITORY');
export const CALENDAR_PROVIDER = Symbol('CALENDAR_PROVIDER');
export const TOKEN_SEALER = Symbol('TOKEN_SEALER');
