export const COMPONENTS = [
  { slug: 'accordion', name: 'Accordion' },
  { slug: 'alert', name: 'Alert' },
  { slug: 'alert-dialog', name: 'Alert Dialog' },
  { slug: 'approval', name: 'Approval' },
  { slug: 'aspect-ratio', name: 'Aspect Ratio' },
  { slug: 'avatar', name: 'Avatar' },
  { slug: 'badge', name: 'Badge' },
  { slug: 'brand-mark', name: 'Brand mark' },
  { slug: 'button', name: 'Button' },
  { slug: 'card', name: 'Card' },
  { slug: 'chat-markdown', name: 'Chat Markdown' },
  { slug: 'checkbox', name: 'Checkbox' },
  { slug: 'collapsible', name: 'Collapsible' },
  { slug: 'combobox', name: 'Combobox' },
  { slug: 'context-menu', name: 'Context Menu' },
  { slug: 'dialog', name: 'Dialog' },
  { slug: 'dropdown-menu', name: 'Dropdown Menu' },
  { slug: 'empty-state', name: 'Empty State' },
  { slug: 'filter-menu', name: 'Filter Menu' },
  { slug: 'hover-card', name: 'Hover Card' },
  { slug: 'input', name: 'Input' },
  { slug: 'label', name: 'Label' },
  { slug: 'mailbox-tag', name: 'Mailbox Tag' },
  { slug: 'menubar', name: 'Menubar' },
  { slug: 'message-list', name: 'Message List' },
  { slug: 'message-reader', name: 'Message Reader' },
  { slug: 'popover', name: 'Popover' },
  { slug: 'progress', name: 'Progress' },
  { slug: 'radio-group', name: 'Radio Group' },
  { slug: 'reply-box', name: 'Reply Box' },
  { slug: 'select', name: 'Select' },
  { slug: 'separator', name: 'Separator' },
  { slug: 'skeleton', name: 'Skeleton' },
  { slug: 'stage-breakdown', name: 'Stage Breakdown' },
  { slug: 'switch', name: 'Switch' },
  { slug: 'tabs', name: 'Tabs' },
  { slug: 'text', name: 'Text' },
  { slug: 'textarea', name: 'Textarea' },
  { slug: 'toggle', name: 'Toggle' },
  { slug: 'toggle-group', name: 'Toggle Group' },
  { slug: 'tool-call', name: 'Tool Call' },
  { slug: 'tooltip', name: 'Tooltip' },
] as const;
