export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const USER_ROLE_REPOSITORY = Symbol('USER_ROLE_REPOSITORY');
export const AUTHZ_VERSION_REPOSITORY = Symbol('AUTHZ_VERSION_REPOSITORY');
